DQTInfo = {}

--[[
Quests Object
	name: name of quest category
	quests:
		quest type -> list of names of quests
--]]

DQTInfo.SummersetQuests = {
	name="Summerset",
	quests={
		["Group Boss"] = {
			L.DQT_SUMMERSET_BOUNTY_1,
			L.DQT_SUMMERSET_BOUNTY_2,
			L.DQT_SUMMERSET_BOUNTY_3,
			L.DQT_SUMMERSET_BOUNTY_4,
			L.DQT_SUMMERSET_BOUNTY_5,
			L.DQT_SUMMERSET_BOUNTY_6
		},
		["Delve"] = {
			L.DQT_SUMMERSET_EXPLORATORY_1,
			L.DQT_SUMMERSET_EXPLORATORY_2,
			L.DQT_SUMMERSET_EXPLORATORY_3,
			L.DQT_SUMMERSET_EXPLORATORY_4,
			L.DQT_SUMMERSET_EXPLORATORY_5,
			L.DQT_SUMMERSET_EXPLORATORY_6
		},
		["Geysers"] = {
			L.DQT_SUMMERSET_GEYSER
		}
	}
}

DQTInfo.VvardenfellQuests = {
	name="Vvardenfell",
	quests={
		["Group Boss"] = {
			L.DQT_VVARDENFELL_BOUNTY_1,
			L.DQT_VVARDENFELL_BOUNTY_2,
			L.DQT_VVARDENFELL_BOUNTY_3,
			L.DQT_VVARDENFELL_BOUNTY_4,
			L.DQT_VVARDENFELL_BOUNTY_5,
			L.DQT_VVARDENFELL_BOUNTY_6
		},
		["Delve"] = {
			L.DQT_VVARDENFELL_EXPLORATORY_1,
			L.DQT_VVARDENFELL_EXPLORATORY_2,
			L.DQT_VVARDENFELL_EXPLORATORY_3,
			L.DQT_VVARDENFELL_EXPLORATORY_4,
			L.DQT_VVARDENFELL_EXPLORATORY_5,
			L.DQT_VVARDENFELL_EXPLORATORY_6
		},
		["Ashlander Hunt"] = {
			L.DQT_VVARDENFELL_HUNT_1,
			L.DQT_VVARDENFELL_HUNT_2,
			L.DQT_VVARDENFELL_HUNT_3,
			L.DQT_VVARDENFELL_HUNT_4,
			L.DQT_VVARDENFELL_HUNT_5,
			L.DQT_VVARDENFELL_HUNT_6,
			L.DQT_VVARDENFELL_HUNT_7
		},
		["Ashlander Relic"] = {
			L.DQT_VVARDENFELL_RELICS_1,
			L.DQT_VVARDENFELL_RELICS_2,
			L.DQT_VVARDENFELL_RELICS_3,
			L.DQT_VVARDENFELL_RELICS_4,
			L.DQT_VVARDENFELL_RELICS_5,
			L.DQT_VVARDENFELL_RELICS_6,
			L.DQT_VVARDENFELL_RELICS_7
		}
	}
}

DQTInfo.GuildQuests = {
	name="Guild",
	quests={
		["Fighters Guild"] = {
			L.DQT_FIGHTERS_GUILD_1,
			L.DQT_FIGHTERS_GUILD_2,
			L.DQT_FIGHTERS_GUILD_3,
			L.DQT_FIGHTERS_GUILD_4,
			L.DQT_FIGHTERS_GUILD_5,
			L.DQT_FIGHTERS_GUILD_6,
			L.DQT_FIGHTERS_GUILD_7,
			L.DQT_FIGHTERS_GUILD_8,
			L.DQT_FIGHTERS_GUILD_9,
			L.DQT_FIGHTERS_GUILD_10,
			L.DQT_FIGHTERS_GUILD_11,
			L.DQT_FIGHTERS_GUILD_12,
			L.DQT_FIGHTERS_GUILD_13,
			L.DQT_FIGHTERS_GUILD_14,
			L.DQT_FIGHTERS_GUILD_15
		},
		["Mages Guild"] = {
			L.DQT_MAGES_GUILD_1,
			L.DQT_MAGES_GUILD_2,
			L.DQT_MAGES_GUILD_3,
			L.DQT_MAGES_GUILD_4,
			L.DQT_MAGES_GUILD_5,
			L.DQT_MAGES_GUILD_6,
			L.DQT_MAGES_GUILD_7,
			L.DQT_MAGES_GUILD_8,
			L.DQT_MAGES_GUILD_9,
			L.DQT_MAGES_GUILD_10,
			L.DQT_MAGES_GUILD_11,
			L.DQT_MAGES_GUILD_12,
			L.DQT_MAGES_GUILD_13,
			L.DQT_MAGES_GUILD_14,
			L.DQT_MAGES_GUILD_15
		},
		["Undaunted Delve"] = {
			L.DQT_UNDAUNTED_DELVE_1,
			L.DQT_UNDAUNTED_DELVE_2,
			L.DQT_UNDAUNTED_DELVE_3,
			L.DQT_UNDAUNTED_DELVE_4,
			L.DQT_UNDAUNTED_DELVE_5,
			L.DQT_UNDAUNTED_DELVE_6,
			L.DQT_UNDAUNTED_DELVE_7,
			L.DQT_UNDAUNTED_DELVE_8,
			L.DQT_UNDAUNTED_DELVE_9,
			L.DQT_UNDAUNTED_DELVE_10,
			L.DQT_UNDAUNTED_DELVE_11,
			L.DQT_UNDAUNTED_DELVE_12,
			L.DQT_UNDAUNTED_DELVE_13,
			L.DQT_UNDAUNTED_DELVE_14,
			L.DQT_UNDAUNTED_DELVE_15
		}
	}
}

DQTInfo.CyrodilicCollectionsQuests = {
	name="Cyrodilic Collections",
	quests={
		[L.DQT_CYRODILIC_COLLECTIONS_1] = {L.DQT_CYRODILIC_COLLECTIONS_1},
		[L.DQT_CYRODILIC_COLLECTIONS_2] = {L.DQT_CYRODILIC_COLLECTIONS_2},
		[L.DQT_CYRODILIC_COLLECTIONS_3] = {L.DQT_CYRODILIC_COLLECTIONS_3},
		[L.DQT_CYRODILIC_COLLECTIONS_4] = {L.DQT_CYRODILIC_COLLECTIONS_4},
		[L.DQT_CYRODILIC_COLLECTIONS_5] = {L.DQT_CYRODILIC_COLLECTIONS_5},
		[L.DQT_CYRODILIC_COLLECTIONS_6] = {L.DQT_CYRODILIC_COLLECTIONS_6}
	}
}

DQTInfo.ClockworkCityQuests = {
	name="Clockwork City",
	quests={
		["Group Boss"] = {
			L.DQT_CWC_BOUNTY_1,
			L.DQT_CWC_BOUNTY_2
		},
		["Delve"] = {
			L.DQT_CWC_EXPLORATORY_1,
			L.DQT_CWC_EXPLORATORY_2,
			L.DQT_CWC_EXPLORATORY_3,
			L.DQT_CWC_EXPLORATORY_4,
			L.DQT_CWC_EXPLORATORY_5,
			L.DQT_CWC_EXPLORATORY_6
		},
		["Tarnished"] = {
			L.DQT_CWC_TARNISHED_1,
			L.DQT_CWC_TARNISHED_2,
			L.DQT_CWC_TARNISHED_3,
			L.DQT_CWC_TARNISHED_4,
			L.DQT_CWC_TARNISHED_5,
			L.DQT_CWC_TARNISHED_6
		},
		["Blackfeather Court"] = {
			L.DQT_CWC_BLACKFEATHER_1,
			L.DQT_CWC_BLACKFEATHER_2,
			L.DQT_CWC_BLACKFEATHER_3,
			L.DQT_CWC_BLACKFEATHER_4,
			L.DQT_CWC_BLACKFEATHER_5,
			L.DQT_CWC_BLACKFEATHER_6
		}
	}
}

DQTInfo.WrothgarQuests = {
	name="Wrothgar",
	quests = {
		["Group Boss"] = {
			L.DQT_WROTHGAR_GROUP_BOSS_1,
			L.DQT_WROTHGAR_GROUP_BOSS_2,
			L.DQT_WROTHGAR_GROUP_BOSS_3,
			L.DQT_WROTHGAR_GROUP_BOSS_4,
			L.DQT_WROTHGAR_GROUP_BOSS_5,
			L.DQT_WROTHGAR_GROUP_BOSS_6
		},
		["Delve"] = {
			L.DQT_WROTHGAR_DELVE_1,
			L.DQT_WROTHGAR_DELVE_2,
			L.DQT_WROTHGAR_DELVE_3,
			L.DQT_WROTHGAR_DELVE_4,
			L.DQT_WROTHGAR_DELVE_5,
			L.DQT_WROTHGAR_DELVE_6
		}
	}
}

DQTInfo.ThievesGuildQuests = {
	name="Thieves Guild",
	quests={
		["Rye's Reacquisitions"] = {
			L.DQT_RYES_REACQUISITIONS_1,
			L.DQT_RYES_REACQUISITIONS_2,
			L.DQT_RYES_REACQUISITIONS_3,
			L.DQT_RYES_REACQUISITIONS_4
		},
		["Heist"] = {
			L.DQT_HEIST_1,
			L.DQT_HEIST_2,
			L.DQT_HEIST_3,
			L.DQT_HEIST_4,
			L.DQT_HEIST_5
		}
	}
}

DQTInfo.DarkBrotherhoodQuests = {
	name="Dark Brotherhood",
	quests={
		["Bounty"] = {
			L.DQT_GOLD_COAST_BOUNTY_1,
			L.DQT_GOLD_COAST_BOUNTY_2,
			L.DQT_GOLD_COAST_BOUNTY_3,
			L.DQT_GOLD_COAST_BOUNTY_4
		},
		["Sacrament"] = {
			L.DQT_SACRAMENT_1,
			L.DQT_SACRAMENT_2,
			L.DQT_SACRAMENT_3
		}
	}
}

DQTInfo.Quests = {
	DQTInfo.SummersetQuests,
	DQTInfo.VvardenfellQuests,
	DQTInfo.CyrodilicCollectionsQuests,
	DQTInfo.GuildQuests,
	DQTInfo.ClockworkCityQuests,
	DQTInfo.WrothgarQuests,
	DQTInfo.ThievesGuildQuests,
	DQTInfo.DarkBrotherhoodQuests
}