-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
-- L is a convenience table so we don't have to write ZO_CreateStringId a bunch of times
local L = {}
local lang = 'de'
local MN = LibMultilingualName

-- Undaunted Pledges. Maj al-Ragath's Pledges
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_01 = GetQuestName(5274) -- "Gelöbnis: Dunkelschattenkavernen I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_02 = GetQuestName(5275) -- "Gelöbnis: Dunkelschattenkavernen II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_03 = GetQuestName(5276) -- "Gelöbnis: Eldengrund I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_04 = GetQuestName(5277) -- "Gelöbnis: Eldengrund II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_05 = GetQuestName(5247) -- "Gelöbnis: Pilzgrotte I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_06 = GetQuestName(5248) -- "Gelöbnis: Pilzgrotte II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_07 = GetQuestName(5260) -- "Gelöbnis: Spindeltiefen I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_08 = GetQuestName(5273) -- "Gelöbnis: Spindeltiefen II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_09 = GetQuestName(5244) -- "Gelöbnis: Verbannungszellen I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_10 = GetQuestName(5246) -- "Gelöbnis: Verbannungszellen II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_11 = GetQuestName(5278) -- "Gelöbnis: Kanalisation von Wegesruh I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_12 = GetQuestName(5282) -- "Gelöbnis: Kanalisation von Wegesruh II"

-- Undaunted Pledges. Glirion the Redbeard's Pledges
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_01 = GetQuestName(5288) -- "Gelöbnis: Arx Corinium"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_02 = GetQuestName(5305) -- "Gelöbnis: Schwarzherz-Unterschlupf"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_03 = GetQuestName(5306) -- "Gelöbnis: Gesegnete Feuerprobe I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_04 = GetQuestName(5290) -- "Gelöbnis: Stadt der Asche I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_05 = GetQuestName(5381) -- "Gelöbnis: Stadt der Asche II"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_06 = GetQuestName(5283) -- "Gelöbnis: Krypta der Herzen I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_07 = GetQuestName(5284) -- "Gelöbnis: Krypta der Herzen II"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_08 = GetQuestName(5291) -- "Gelöbnis: Burg Grauenfrost I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_09 = GetQuestName(5307) -- "Gelöbnis: Selenes Netz"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_10 = GetQuestName(5301) -- "Gelöbnis: Orkaninsel"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_11 = GetQuestName(5309) -- "Gelöbnis: Kammern des Wahnsinns"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_12 = GetQuestName(5303) -- "Gelöbnis: Volenfell"

-- Undaunted Pledges. Urgarlag Chief-bane's Pledges
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_01 = GetQuestName(6053) -- "Gelöbnis: Blutquellschmiede"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_02 = GetQuestName(5780) -- "Gelöbnis: Wiege der Schatten"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_03 = GetQuestName(6054) -- "Gelöbnis: Falkenring"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_04 = GetQuestName(6155) -- "Gelöbnis: Krallenhort"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_05 = GetQuestName(5382) -- "Gelöbnis: Gefängnis der Kaiserstadt"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_06 = GetQuestName(6189) -- "Gelöbnis: Marsch der Aufopferung"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_07 = GetQuestName(6187) -- "Gelöbnis: Mondjägerfeste"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_08 = GetQuestName(5636) -- "Gelöbnis: Ruinen von Mazzatun"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_09 = GetQuestName(6154) -- "Gelöbnis: Gipfel der Schuppenruferin"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_10 = GetQuestName(5431) -- "Gelöbnis: Weißgoldturm"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_11 = GetQuestName(6250) -- "Pledge: Frostvault"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_12 = GetQuestName(6252) -- "Pledge: Depths of Malatar"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_13 = GetQuestName(6352) -- "Pledge: Lair of Maarselok"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_14 = GetQuestName(6350) -- "Pledge: Moongrave Fane"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_15 = GetQuestName(6415) -- "Pledge: Icereach"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_16 = GetQuestName(6417) -- "Pledge: Unhallowed Grave"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_17 = GetQuestName(6508) -- "Pledge: Castle Thorn"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_18 = GetQuestName(6506) -- "Pledge: Stone Garden"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_19 = GetQuestName(6577) -- "Pledge: Black Drake Villa"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_20 = GetQuestName(6579) -- "Pledge: The Cauldron"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_21 = GetQuestName(6684) -- "Pledge: Red Petal Bastion"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_22 = GetQuestName(6686) -- "Pledge: The Dread Cellar"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_23 = GetQuestName(6741) -- "Pledge: Coral Aerie"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_24 = GetQuestName(6743) -- "Pledge: Shipwright's Regret"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_25 = GetQuestName(6836) -- "Pledge: Earthen Root Enclave"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_26 = GetQuestName(6838) -- "Pledge: Graven Deep"

-- Guild Daily Quests. Fighters Guild Daily Quests
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_01 = GetQuestName(5786) -- "Dunkle Anker in der Alik'r-Wüste"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_02 = GetQuestName(5793) -- "Dunkle Anker in Auridon"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_03 = GetQuestName(5787) -- "Dunkle Anker in Bangkorai"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_04 = GetQuestName(5789) -- "Dunkle Anker in Deshaan"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_05 = GetQuestName(5791) -- "Dunkle Anker in Ostmarsch"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_06 = GetQuestName(5833) -- "Dunkle Anker in Glenumbra"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_07 = GetQuestName(5794) -- "Dunkle Anker in Grahtwald"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_08 = GetQuestName(5796) -- "Dunkle Anker in Grünschatten"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_09 = GetQuestName(5795) -- "Dunkle Anker in Malabal Tor"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_10 = GetQuestName(5797) -- "Dunkle Anker in Schnittermark"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_11 = GetQuestName(5785) -- "Dunkle Anker in Kluftspitze"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_12 = GetQuestName(5790) -- "Dunkle Anker in Schattenfenn"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_13 = GetQuestName(5788) -- "Dunkle Anker in Steinfälle"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_14 = GetQuestName(5784) -- "Dunkle Anker in Sturmhafen"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_15 = GetQuestName(5792) -- "Dunkle Anker in Rift"

-- Guild Daily Quests. Mages Guild Daily Quests
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_01 = GetQuestName(5814) -- "Verrückte Alik'r Wüste"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_02 = GetQuestName(5816) -- "Verrücktes Auridon"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_03 = GetQuestName(5818) -- "Verrücktes Bangkorai"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_04 = GetQuestName(5819) -- "Verrücktes Deshaan"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_05 = GetQuestName(5820) -- "Verrücktes Ostmarsch"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_06 = GetQuestName(5822) -- "Verrücktes Glenumbra"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_07 = GetQuestName(5823) -- "Verrücktes Grahtwald"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_08 = GetQuestName(5824) -- "Verrücktes Grünschatten"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_09 = GetQuestName(5825) -- "Verrücktes Malabal Tor"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_10 = GetQuestName(5826) -- "Verrücktes Schnittermark"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_11 = GetQuestName(5827) -- "Verrücktes Kluftspitze"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_12 = GetQuestName(5828) -- "Verrücktes Schattenfenn"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_13 = GetQuestName(5829) -- "Verrücktes Steinfälle"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_14 = GetQuestName(5830) -- "Verrücktes Sturmhafen"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_15 = GetQuestName(5831) -- "Verrücktes Rift"

-- Guild Daily Quests. Undaunted Daily Quests
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_01 = GetQuestName(5735) -- "Ahnenschutzzauber in Deshaan"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_02 = GetQuestName(5733) -- "Alte Rüstungen aus Bangkorai"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_03 = GetQuestName(5738) -- "Ayleïdenschnickschnack in Grahtwald"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_04 = GetQuestName(5853) -- "Kulinarische Gerechtigkeit in Grünschatten"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_05 = GetQuestName(5800) -- "Sturmhafens verfluchter Tand"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_06 = GetQuestName(5808) -- "Dunkle Blüte in Kluftspitze"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_07 = GetQuestName(5737) -- "Dwemerrelikte aus Steinfälle"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_08 = GetQuestName(5778) -- "Geben und Nehmen in Schattenfenn"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_09 = GetQuestName(5779) -- "Eisige Intrige in Ostmarsch"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_10 = GetQuestName(5802) -- "Die brennenden Feuer von Rift"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_11 = GetQuestName(5744) -- "Maskottchendieb von Schnittermark"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_12 = GetQuestName(5745) -- "Geschmolzene Perlen der Alik'r-Wüste"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_13 = GetQuestName(5739) -- "Rotkrähen-Plünderung in Glenumbra"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_14 = GetQuestName(5734) -- "Die Geisterfalle in Malabal Tor"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_15 = GetQuestName(5798) -- "Verschleierte Finsternis in Auridon"

-- Crafting Writs. Consumables Crafting Writs
L.SI_DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_01 = GetQuestName(6105) -- "Alchemist Writ"
L.SI_DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_02 = GetQuestName(5407) -- "Enchanter Writ"
L.SI_DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_03 = GetQuestName(5414) -- "Provisioner Writ"

-- Crafting Writs. Equipment Crafting Writs
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_01 = GetQuestName(5377) -- "Blacksmith Writ"
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_02 = GetQuestName(5374) -- "Clothier Writ"
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_03 = GetQuestName(6228) -- "Jewelry Crafting Writ"
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_04 = GetQuestName(5395) -- "Woodworker Writ"

-- Crafting Writs. Master Writs
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_01 = GetQuestName(5991) -- "A Masterful Concoction"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_02 = GetQuestName(5977) -- "A Masterful Feast"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_03 = GetQuestName(6017) -- "A Masterful Glyph"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_04 = GetQuestName(6022) -- "Masterful Leatherwear"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_05 = GetQuestName(6018) -- "A Masterful Plate"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_06 = GetQuestName(6020) -- "A Masterful Shield"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_07 = GetQuestName(6021) -- "Masterful Tailoring"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_08 = GetQuestName(6452) -- "Masterful Jewelry"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_09 = GetQuestName(5972) -- "A Masterful Weapon"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_10 = GetQuestName(5975) -- "A Masterful Weapon"

-- Craglorn Quests. Lower Craglorn
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_01 = GetQuestName(5756) -- "Critical Mass"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_02 = GetQuestName(5750) -- "The Fallen City of Shada"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_03 = GetQuestName(5762) -- "The Reason We Fight"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_04 = GetQuestName(5749) -- "The Seeker's Archive"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_05 = GetQuestName(5755) -- "Supreme Power"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_06 = GetQuestName(5751) -- "The Trials of Rahni'Za"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_07 = GetQuestName(5754) -- "Waters Run Foul"

-- Craglorn Quests. Upper Craglorn
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_01 = GetQuestName(5767) -- "The Blood of Nirn"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_02 = GetQuestName(5777) -- "The Gray Passage"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_03 = GetQuestName(5766) -- "Iron and Scales"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_04 = GetQuestName(5770) -- "Souls of the Betrayed"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_05 = GetQuestName(5765) -- "Taken Alive"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_06 = GetQuestName(5764) -- "The Truer Fangs"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_07 = GetQuestName(5772) -- "Uncaged"

-- Black Marsh. Cyrodilic Collections
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_01 = GetQuestName(6263) -- "Ein giftiger Geschmack"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_02 = GetQuestName(6255) -- "Viel Lärm um ein Gegengift"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_03 = GetQuestName(6257) -- "Blöde Mücken!"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_04 = GetQuestName(6256) -- "Rekrutierungsrunde"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_05 = GetQuestName(6260) -- "Salzfleisch"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_06 = GetQuestName(6261) -- "Die Winde von Kyne"

-- Imperial City. Imperial City Quests
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_01 = GetQuestName(5500) -- "Dousing the Fires of Industry"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_02 = GetQuestName(5498) -- "Historical Accuracy"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_03 = GetQuestName(5492) -- "The Lifeblood of an Empire"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_04 = GetQuestName(5495) -- "Priceless Treasures"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_05 = GetQuestName(5491) -- "Speaking For The Dead"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_06 = GetQuestName(5501) -- "Watch Your Step"

-- Wrothgar Quests. Delve Dailies
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_01 = GetQuestName(5507) -- "Ein bizarres Frühstück"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_02 = GetQuestName(5505) -- "Feuer in der Feste"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_03 = GetQuestName(5515) -- "Freie Geister"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_04 = GetQuestName(5514) -- "Der volle Bauch"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_05 = GetQuestName(5509) -- "Teile des Ganzen"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_06 = GetQuestName(5504) -- "Das Geschäft mit der Haut"

-- Wrothgar Quests. Group Boss Dailies
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_01 = GetQuestName(5522) -- "Der Frevel des Unwissens"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_02 = GetQuestName(5518) -- "Fleisch für die Massen"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_03 = GetQuestName(5521) -- "Die Gabe der Natur"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_04 = GetQuestName(5524) -- "So riecht ein falsches Spiel"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_05 = GetQuestName(5519) -- "Gelehrtes Bergungsgut"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_06 = GetQuestName(5523) -- "Schnee und Dampf"

-- Thieves Guild Larceny Quests. Guild Jobs
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_01 = GetQuestName(5584) -- "Die gierige Gräfin"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_02 = GetQuestName(5647) -- "Verbrechensserie"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_03 = GetQuestName(5640) -- "Müßiggang"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_04 = GetQuestName(5642) -- "Zupfende Finger"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_05 = GetQuestName(5644) -- "Unter unserer Knute"

-- Thieves Guild Larceny Quests. Rye's Reacquisitions
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_01 = GetQuestName(5586) -- "Die verschwundenen Perlen"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_02 = GetQuestName(5588) -- "Erinnerungen an die Jugend"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_03 = GetQuestName(5589) -- "Die Seemannspfeife"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_04 = GetQuestName(5587) -- "Sklavenbucht^fd,in"

-- Thieves Guild Larceny Quests. Heists
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_01 = GetQuestName(5536) -- "Beutezug der Todkuhlenhallen"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_02 = GetQuestName(5575) -- "Beutezug der funkelnden Grotte"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_03 = GetQuestName(5572) -- "Beutezug des Verstecks"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_04 = GetQuestName(5577) -- "Beutezug der abgelegenen Kanalisation"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_05 = GetQuestName(5573) -- "Beutezug der unterirdischen Grabstätte"

-- Gold Coast Quests. Bounties
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_01 = GetQuestName(5603) -- "Das Übel unter der Erde"
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_02 = GetQuestName(5604) -- "Das Gemeinwohl"
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_03 = GetQuestName(5605) -- "Drohende Schatten"
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_04 = GetQuestName(5606) -- "Das Jubeln der Menge"

-- Gold Coast Quests. Dark Brotherhood Contracts
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_01 = GetQuestName(5627) -- "Kontrakt: Alik'r-Wüste"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_02 = GetQuestName(5693) -- "Kontrakt: Alik'r-Wüsten-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_03 = GetQuestName(5657) -- "Kontrakt: Auridon"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_04 = GetQuestName(5694) -- "Kontrakt: Auridon-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_05 = GetQuestName(5632) -- "Kontrakt: Bangkorai"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_06 = GetQuestName(5696) -- "Kontrakt: Bangkorai-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_07 = GetQuestName(5652) -- "Kontrakt: Deshaan"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_08 = GetQuestName(5698) -- "Kontrakt: Deshaan-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_09 = GetQuestName(5670) -- "Kontrakt: Ostmarsch"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_10 = GetQuestName(5699) -- "Kontrakt: Ostmarsch-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_11 = GetQuestName(5594) -- "Kontrakt: Glenumbra"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_12 = GetQuestName(5700) -- "Kontrakt: Glenumbra-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_13 = GetQuestName(5688) -- "Kontrakt: Goldküsten-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_14 = GetQuestName(5672) -- "Kontrakt: Grahtwald"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_15 = GetQuestName(5701) -- "Kontrakt: Grahtwald-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_16 = GetQuestName(5677) -- "Kontrakt: Grünschatten"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_17 = GetQuestName(5703) -- "Kontrakt: Grünschatten-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_18 = GetQuestName(5665) -- "Kontrakt: Malabal Tor"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_19 = GetQuestName(5704) -- "Kontrakt: Malabal-Tor-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_20 = GetQuestName(5680) -- "Kontrakt: Schnittermark"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_21 = GetQuestName(5705) -- "Kontrakt: Schnittermark-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_22 = GetQuestName(5626) -- "Kontrakt: Kluftspitze"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_23 = GetQuestName(5706) -- "Kontrakt: Kluftspitzen-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_24 = GetQuestName(5684) -- "Kontrakt: Schattenfenn"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_25 = GetQuestName(5707) -- "Kontrakt: Schattenfenn-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_26 = GetQuestName(5690) -- "Kontrakt: Steinfälle"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_27 = GetQuestName(5709) -- "Kontrakt: Steinfälle-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_28 = GetQuestName(5621) -- "Kontrakt: Sturmhafen"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_29 = GetQuestName(5710) -- "Kontrakt: Sturmhafen-Massaker"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_30 = GetQuestName(5697) -- "Kontrakt: Rift"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_31 = GetQuestName(5711) -- "Kontrakt: Rift-Massaker"

-- Gold Coast Quests. Dark Brotherhood Sacraments
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_01 = GetQuestName(5720) -- "Sakrament: Schmugglernest"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_02 = GetQuestName(5726) -- "Sakrament: Kanalbehausung"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_03 = GetQuestName(5714) -- "Sakrament: Händlerbucht"

-- Vvardenfell Quests. Bounty
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_01 = GetQuestName(5916) -- "Der besorgte Lehrling"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_02 = GetQuestName(5918) -- "Ein schleichender Hunger"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_03 = GetQuestName(5865) -- "Das Ausdünnen des Schwarms"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_04 = GetQuestName(5866) -- "Frei laufende Ochsen"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_05 = GetQuestName(5904) -- "Salothans Fluch"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_06 = GetQuestName(5906) -- "Sirenensang"

-- Vvardenfell Quests. Exploratory
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_01 = GetQuestName(5956) -- "Daedrische Störungen"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_02 = GetQuestName(5962) -- "Quatsch mit Kwama"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_03 = GetQuestName(5961) -- "Das Streuen von Fehlinformationen"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_04 = GetQuestName(5934) -- "Steuerabzug"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_05 = GetQuestName(5915) -- "Stammessorgen"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_06 = GetQuestName(5958) -- "Ein Syndikat in Unruhe"

-- Vvardenfell Quests. Hunt
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_01 = GetQuestName(5911) -- "Jagd auf Aschfresser"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_02 = GetQuestName(5907) -- "Jagd auf den Großen Zexxin"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_03 = GetQuestName(5913) -- "Jagd auf König Klingenhauer"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_04 = GetQuestName(5910) -- "Jagd auf Mutter Zackige-Klaue"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_05 = GetQuestName(5912) -- "Jagd auf Alter Stampfer"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_06 = GetQuestName(5908) -- "Jagd auf Tarra-Suj"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_07 = GetQuestName(5909) -- "Jagd auf den Sich Windenden Sveeth"

-- Vvardenfell Quests. Relics
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_01 = GetQuestName(5930) -- "Die Relikte von Ashalmawia"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_02 = GetQuestName(5927) -- "Die Relikte von Ashurnabitashpi"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_03 = GetQuestName(5925) -- "Die Relikte von Assarnatamat"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_04 = GetQuestName(5929) -- "Die Relikte von Dushariran"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_05 = GetQuestName(5928) -- "Relikte von Ebernanit"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_06 = GetQuestName(5926) -- "Die Relikte von Maelkashishi"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_07 = GetQuestName(5924) -- "Die Relikte von Yasammidan"

-- Clockwork City Quests. Bounty
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BOUNTY_01 = GetQuestName(6077) -- "Ein feingefiederter Feind"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BOUNTY_02 = GetQuestName(6076) -- "Das Reizen des Unvollendeten"

-- Clockwork City Quests. Exploratory
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_01 = GetQuestName(6088) -- "Filterwechsel"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_02 = GetQuestName(6081) -- "Die Ventilatoren ölen"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_03 = GetQuestName(6089) -- "Gleichrichterersatz"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_04 = GetQuestName(6079) -- "Zurück in die Schatten"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_05 = GetQuestName(6080) -- "Eine schattige Fehlfunktion"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_06 = GetQuestName(6073) -- "Ein verlegter Schatten"

-- Clockwork City Quests. Tarnished
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_01 = GetQuestName(6042) -- "Eine bittere Pille"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_02 = GetQuestName(6038) -- "Das tägliche Zermahlen"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_03 = GetQuestName(6040) -- "Eine klebrige Lösung"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_04 = GetQuestName(6041) -- "Verzauberte Ansammlung"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_05 = GetQuestName(6037) -- "Brennstoff für unsere Feuer"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_06 = GetQuestName(6039) -- "Lose Fasern"

-- Clockwork City Quests. Blackfeather Court
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_01 = GetQuestName(6024) -- "Glitzern und Funkeln"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_02 = GetQuestName(6107) -- "Eine Frage der Muße"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_03 = GetQuestName(6072) -- "Eine Frage des Respekts"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_04 = GetQuestName(6106) -- "Eine Frage des Tributs"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_05 = GetQuestName(6071) -- "Bröckchen und Bisschen"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_06 = GetQuestName(6070) -- "Stückchen und Häppchen"

-- Summerset Quests. Bounty
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_01 = GetQuestName(6084) -- "Der Kluftalchemist"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_02 = GetQuestName(6085) -- "Vom gleichen Schlag"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_03 = GetQuestName(6086) -- "Nie vergessen"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_04 = GetQuestName(6087) -- "Auf Grund gelaufen"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_05 = GetQuestName(6082) -- "Die Seuchensee"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_06 = GetQuestName(6083) -- "Die Zähmung der Wildnis"

-- Summerset Quests. Exploratory
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_01 = GetQuestName(6159) -- "Schlangentöter"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_02 = GetQuestName(6152) -- "Das Ende der Pilgerfahrt"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_03 = GetQuestName(6158) -- "Die Reliktrettung"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_04 = GetQuestName(6157) -- "Die Schönheit einer Rose"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_05 = GetQuestName(6156) -- "Das Verlöschen des Lichts"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_06 = GetQuestName(6160) -- "Aus der Erinnerung getilgt"

-- Summerset Quests. Abyssal Geysers
L.SI_DQT_SUMMERSET_QUESTS_ABYSSAL_GEYSERS_01 = GetQuestName(6202) -- "Die Versenkung Sommersends"

-- Murkmire Quests. Bounty
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_01 = GetQuestName(6233) -- "Tödliche Umstände"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_02 = GetQuestName(6236) -- "Tödliche Erwartungen"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_03 = GetQuestName(6237) -- "Tödliche Erinnerungsstücke"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_04 = GetQuestName(6235) -- "Alter Tand"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_05 = GetQuestName(6238) -- "Alte Feinde"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_06 = GetQuestName(6234) -- "Alter Wuchs"

-- Murkmire Quests. Exploratory
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_01 = GetQuestName(6253) -- "Antike Rüstungen"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_02 = GetQuestName(6268) -- "Todernste Angelegenheiten"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_03 = GetQuestName(6248) -- "Alte Schriftrollen"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_04 = GetQuestName(6264) -- "Heilige Kerzen"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_05 = GetQuestName(6267) -- "Werkzeuge des Gemetzels"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_06 = GetQuestName(6247) -- "Die Last der Worte"

-- Murkmire Quests. Root-Whisper
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_01 = GetQuestName(6286) -- "Aloe, die heilt"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_02 = GetQuestName(6288) -- "Gesandte, die kuschen"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_03 = GetQuestName(6290) -- "Leder, das schützt"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_04 = GetQuestName(6287) -- "Pilze, die nähren"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_05 = GetQuestName(6289) -- "Opfergaben, die sich verbergen"

-- Cyrodiil. Cyrodiil Settlement Quests. Bruma
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_01 = GetQuestName(4561) -- "Gefährliche Neige"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_02 = GetQuestName(4563) -- "Kappsteinkappen"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_03 = GetQuestName(4564) -- "Einsam und allein"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_04 = GetQuestName(4568) -- "Die Menhire"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_05 = GetQuestName(4569) -- "Feindliche Verstärkung"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_06 = GetQuestName(4570) -- "Kennet Euren Feind"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_07 = GetQuestName(4572) -- "Hilfsgesuche"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_08 = GetQuestName(4579) -- "Das Ende des Magisters"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_09 = GetQuestName(4581) -- "Die Ungesehenen"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_10 = GetQuestName(4591) -- "Zeitiges Eingreifen"

-- Cyrodiil. Cyrodiil Settlement Quests. Cheydinhal
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_01 = GetQuestName(4421) -- "Dornen in unserer Seite"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_02 = GetQuestName(4422) -- "Gewürz"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_03 = GetQuestName(4425) -- "Kriegsgefangene"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_04 = GetQuestName(4430) -- "Das ausgebrannte Anwesen"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_05 = GetQuestName(4433) -- "Der Ayleïdenschatz"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_06 = GetQuestName(4417) -- "Blutige Wasser"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_07 = GetQuestName(4420) -- "Andenken"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_08 = GetQuestName(4424) -- "Eine fällige Schuld"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_09 = GetQuestName(4426) -- "Chancenverbesserung"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_10 = GetQuestName(4434) -- "Um der Frömmigkeit willen"

-- Cyrodiil. Cyrodiil Settlement Quests. Chorrol and Weynon Priory
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_01 = GetQuestName(4226) -- "Tod den Schwarzdolchen"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_02 = GetQuestName(4247) -- "Ein echter Wachdienst geht nie vorüber"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_03 = GetQuestName(4263) -- "Das Feld des Feuers"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_04 = GetQuestName(4265) -- "Der hohe Preis der Lüge"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_05 = GetQuestName(4270) -- "Das Versteck"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_06 = GetQuestName(4224) -- "Abscheulichkeiten"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_07 = GetQuestName(4228) -- "Die Kralle von Akatosh"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_08 = GetQuestName(4238) -- "Überfällige Vorräte"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_09 = GetQuestName(4242) -- "Der Lich"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_10 = GetQuestName(4244) -- "Vorräte der Schwarzdolche"

-- Cyrodiil. Cyrodiil Settlement Quests. Cropsford
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_01 = GetQuestName(4505) -- "Die Saat der Hoffnung"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_02 = GetQuestName(4507) -- "Opfergaben an Zenithar"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_03 = GetQuestName(4509) -- "Erntezeit"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_04 = GetQuestName(4512) -- "Die Toten von Culotte"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_05 = GetQuestName(4517) -- "Kronspitz^N,in"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_06 = GetQuestName(4520) -- "Die Spione der Bluthand"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_07 = GetQuestName(4522) -- "Das Hedoran-Anwesen"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_08 = GetQuestName(4527) -- "Das bewahrte Wissen"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_09 = GetQuestName(4540) -- "Widrigkeiten in der Waldkerbgrube"

-- Cyrodiil. Cyrodiil Settlement Quests. Vlastarus
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_01 = GetQuestName(4048) -- "Der direkte Weg"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_02 = GetQuestName(4052) -- "Die Vettel muss sterben"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_03 = GetQuestName(4065) -- "Eine böse Präsenz"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_04 = GetQuestName(4066) -- "Unverzichtbärige Dinge"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_05 = GetQuestName(4068) -- "Erinnerungsstücke"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_06 = GetQuestName(4072) -- "Felsknochendiplomatie"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_07 = GetQuestName(4073) -- "Das gestohlene Banner"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_08 = GetQuestName(4074) -- "Für einen Freund"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_09 = GetQuestName(4079) -- "Die Essenz der Flamme"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_10 = GetQuestName(4081) -- "Silberschuppen"

-- Cyrodiil. Fighters Guild Bounty Quests
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_01 = GetQuestName(4877) -- "Kopfgeld: Die Schwarzdolche"
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_02 = GetQuestName(4880) -- "Kopfgeld: Die Goblins"
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_03 = GetQuestName(4878) -- "Kopfgeld: Die Grauvipern"
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_04 = GetQuestName(4879) -- "Kopfgeld: Der Schattenpfad"

-- Cyrodiil. PvP Quests. Battle Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_01 = GetQuestName(3206) -- "Erobert den Alessia-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_02 = GetQuestName(3244) -- "Erobert das Alessia-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_03 = GetQuestName(3262) -- "Erobert die Alessia-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_04 = GetQuestName(3198) -- "Erobert den Alebrunn-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_05 = GetQuestName(3236) -- "Erobert das Alebrunn-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_06 = GetQuestName(3254) -- "Erobert die Alebrunn-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_07 = GetQuestName(3201) -- "Erobert den Arrius-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_08 = GetQuestName(3239) -- "Erobert das Arrius-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_09 = GetQuestName(3257) -- "Erobert die Arrius-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_10 = GetQuestName(3197) -- "Erobert den Asch-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_11 = GetQuestName(3234) -- "Erobert das Asch-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_12 = GetQuestName(3253) -- "Erobert die Asch-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_13 = GetQuestName(3210) -- "Erobert den Schwarzstiefel-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_14 = GetQuestName(3248) -- "Erobert das Schwarzstiefel-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_15 = GetQuestName(3268) -- "Erobert die Schwarzstiefel-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_16 = GetQuestName(2970) -- "Erobert den Blutmähne-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_17 = GetQuestName(3249) -- "Erobert das Blutmähne-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_18 = GetQuestName(3269) -- "Erobert die Blutmähne-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_19 = GetQuestName(3204) -- "Erobert den Blauweg-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_20 = GetQuestName(3242) -- "Erobert das Blauweg-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_21 = GetQuestName(3260) -- "Erobert die Blauweg-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_22 = GetQuestName(3209) -- "Erobert den Brindell-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_23 = GetQuestName(3247) -- "Erobert das Brindell-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_24 = GetQuestName(3266) -- "Erobert die Brindell-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_25 = GetQuestName(3200) -- "Erobert den Chalman-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_26 = GetQuestName(3238) -- "Erobert das Chalman-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_27 = GetQuestName(3256) -- "Erobert die Chalman-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_28 = GetQuestName(2958) -- "Erobert den Drachenklaue-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_29 = GetQuestName(3237) -- "Erobert das Drachenklaue-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_30 = GetQuestName(3255) -- "Erobert die Drachenklaue-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_31 = GetQuestName(3205) -- "Erobert den Drakenschein-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_32 = GetQuestName(3243) -- "Erobert das Drakenschein-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_33 = GetQuestName(2944) -- "Erobert die Drakenschein-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_34 = GetQuestName(3207) -- "Erobert den Faregyl-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_35 = GetQuestName(3245) -- "Erobert das Faregyl-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_36 = GetQuestName(3263) -- "Erobert die Faregyl-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_37 = GetQuestName(3203) -- "Erobert den Farragut-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_38 = GetQuestName(3241) -- "Erobert das Farragut-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_39 = GetQuestName(3259) -- "Erobert die Farragut-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_40 = GetQuestName(3196) -- "Erobert den Aunebel-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_41 = GetQuestName(3233) -- "Erobert das Aunebel-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_42 = GetQuestName(3252) -- "Erobert die Aunebel-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_43 = GetQuestName(3202) -- "Erobert den Königsbanner-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_44 = GetQuestName(3240) -- "Erobert das Königsbanner-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_45 = GetQuestName(3258) -- "Erobert die Königsbanner-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_46 = GetQuestName(3102) -- "Erobert den Rayles-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_47 = GetQuestName(3140) -- "Erobert das Rayles-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_48 = GetQuestName(3251) -- "Erobert die Rayles-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_49 = GetQuestName(3208) -- "Erobert den Roebeck-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_50 = GetQuestName(3246) -- "Erobert das Roebeck-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_51 = GetQuestName(3265) -- "Erobert die Roebeck-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_52 = GetQuestName(3194) -- "Erobert den Obhut-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_53 = GetQuestName(2972) -- "Erobert das Obhut-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_54 = GetQuestName(3250) -- "Erobert die Obhut-Mine"

-- Cyrodiil. PvP Quests. Bounty Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_01 = GetQuestName(5228) -- "Tötet feindliche Drachenritter"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_02 = GetQuestName(5231) -- "Tötet feindliche Nachtklingen"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_03 = GetQuestName(4349) -- "Tötet feindliche Spieler"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_04 = GetQuestName(5234) -- "Tötet feindliche Zauberer"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_05 = GetQuestName(5222) -- "Tötet feindliche Templer"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_06 = GetQuestName(6012) -- "Tötet feindliche Hüter"

-- Cyrodiil. PvP Quests. Conquest Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_01 = GetQuestName(6207) -- "Capture All 3 Towns"
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_02 = GetQuestName(6208) -- "Capture Any Nine Resources"
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_03 = GetQuestName(6210) -- "Capture All Three Keeps"
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_04 = GetQuestName(6209) -- "Kill 40 Enemy Players"

-- Cyrodiil. PvP Quests. Scouting Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_01 = GetQuestName(2816) -- "Erkundet den Alessia-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_02 = GetQuestName(2893) -- "Erkundet das Alessia-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_03 = GetQuestName(2870) -- "Erkundet die Alessia-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_04 = GetQuestName(2808) -- "Erkundet den Alebrunn-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_05 = GetQuestName(2826) -- "Erkundet das Alebrunn-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_06 = GetQuestName(2862) -- "Erkundet die Alebrunn-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_07 = GetQuestName(2811) -- "Erkundet den Arrius-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_08 = GetQuestName(2847) -- "Erkundet die Burg Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_09 = GetQuestName(2829) -- "Erkundet das Arrius-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_10 = GetQuestName(2865) -- "Erkundet die Arrius-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_11 = GetQuestName(2807) -- "Erkundet den Asch-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_12 = GetQuestName(2825) -- "Erkundet das Asch-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_13 = GetQuestName(2861) -- "Erkundet die Asch-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_14 = GetQuestName(2820) -- "Erkundet den Schwarzstiefel-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_15 = GetQuestName(2838) -- "Erkundet das Schwarzstiefel-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_16 = GetQuestName(2802) -- "Erkundet die Schwarzstiefel-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_17 = GetQuestName(2821) -- "Erkundet den Blutmähne-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_18 = GetQuestName(2839) -- "Erkundet das Blutmähne-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_19 = GetQuestName(2803) -- "Erkundet die Blutmähne-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_20 = GetQuestName(2814) -- "Erkundet den Blauweg-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_21 = GetQuestName(2850) -- "Erkundet die Burg Blauweg"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_22 = GetQuestName(2832) -- "Erkundet das Blauweg-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_23 = GetQuestName(2868) -- "Erkundet die Blauweg-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_24 = GetQuestName(2819) -- "Erkundet den Brindell-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_25 = GetQuestName(2837) -- "Erkundet das Brindell-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_26 = GetQuestName(2801) -- "Erkundet die Brindell-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_27 = GetQuestName(2852) -- "Erkundet das Kastell Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_28 = GetQuestName(2856) -- "Erkundet das Kastell Schwarzstiefel"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_29 = GetQuestName(2857) -- "Erkundet das Kastell Blutmähne"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_30 = GetQuestName(2855) -- "Erkundet das Kastell Brindell"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_31 = GetQuestName(2853) -- "Erkundet das Kastell Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_32 = GetQuestName(2854) -- "Erkundet das Kastell Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_33 = GetQuestName(2810) -- "Erkundet den Chalman-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_34 = GetQuestName(2846) -- "Erkundet die Burg Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_35 = GetQuestName(2828) -- "Erkundet das Chalman-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_36 = GetQuestName(2864) -- "Erkundet die Chalman-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_37 = GetQuestName(2809) -- "Erkundet den Drachenklaue-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_38 = GetQuestName(2827) -- "Erkundet das Drachenklaue-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_39 = GetQuestName(2863) -- "Erkundet die Drachenklaue-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_40 = GetQuestName(2815) -- "Erkundet den Drakenschein-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_41 = GetQuestName(2851) -- "Erkundet die Burg Drakenschein"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_42 = GetQuestName(2833) -- "Erkundet das Drakenschein-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_43 = GetQuestName(2869) -- "Erkundet die Drakenschein-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_44 = GetQuestName(2817) -- "Erkundet den Faregyl-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_45 = GetQuestName(2835) -- "Erkundet das Faregyl-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_46 = GetQuestName(2871) -- "Erkundet die Faregyl-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_47 = GetQuestName(2813) -- "Erkundet den Farragut-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_48 = GetQuestName(2849) -- "Erkundet die Burg Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_49 = GetQuestName(2831) -- "Erkundet das Farragut-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_50 = GetQuestName(2867) -- "Erkundet die Farragut-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_51 = GetQuestName(2844) -- "Erkundet die Feste Alebrunn"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_52 = GetQuestName(2843) -- "Erkundet die Feste Asch"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_53 = GetQuestName(2845) -- "Erkundet die Feste Drachenklaue"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_54 = GetQuestName(2842) -- "Erkundet die Feste Aunebel"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_55 = GetQuestName(2841) -- "Erkundet die Feste Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_56 = GetQuestName(2840) -- "Kundschaftet die Feste Obhut aus"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_57 = GetQuestName(2806) -- "Erkundet den Aunebel-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_58 = GetQuestName(2824) -- "Erkundet das Aunebel-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_59 = GetQuestName(2860) -- "Erkundet die Aunebel-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_60 = GetQuestName(2812) -- "Erkundet den Königsbanner-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_61 = GetQuestName(2848) -- "Erkundet die Burg Königsbanner"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_62 = GetQuestName(2830) -- "Erkundet das Königsbanner-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_63 = GetQuestName(2866) -- "Erkundet die Königsbanner-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_64 = GetQuestName(2805) -- "Erkundet den Rayles-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_65 = GetQuestName(2823) -- "Erkundet das Rayles-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_66 = GetQuestName(2859) -- "Erkundet die Rayles-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_67 = GetQuestName(2818) -- "Erkundet den Roebeck-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_68 = GetQuestName(2836) -- "Erkundet das Roebeck-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_69 = GetQuestName(2800) -- "Erkundet die Roebeck-Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_70 = GetQuestName(2804) -- "Erkundet den Obhut-Bauernhof"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_71 = GetQuestName(2822) -- "Erkundet das Obhut-Holzfällerlager"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_72 = GetQuestName(2858) -- "Erkundet die Obhut-Mine"

-- Cyrodiil. PvP Quests. Warfront Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_01 = GetQuestName(2927) -- "Erobert das Kastell Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_02 = GetQuestName(2931) -- "Erobert das Kastell Schwarzstiefel"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_03 = GetQuestName(2932) -- "Erobert das Kastell Blutmähne"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_04 = GetQuestName(2930) -- "Erobert das Kastell Brindell"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_05 = GetQuestName(2928) -- "Erobert das Kastell Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_06 = GetQuestName(2929) -- "Erobert das Kastell Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_07 = GetQuestName(2919) -- "Erobert die Feste Alebrunn"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_08 = GetQuestName(2918) -- "Erobert die Feste Asch"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_09 = GetQuestName(2920) -- "Erobert die Feste Drachenklaue"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_10 = GetQuestName(2917) -- "Erobert die Feste Aunebel"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_11 = GetQuestName(2916) -- "Erobert die Feste Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_12 = GetQuestName(2915) -- "Erobert die Feste Obhut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_13 = GetQuestName(2922) -- "Erobert die Burg Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_14 = GetQuestName(2925) -- "Erobert die Burg Blauweg"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_15 = GetQuestName(2921) -- "Erobert die Burg Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_16 = GetQuestName(2926) -- "Erobert die Burg Drakenschein"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_17 = GetQuestName(2924) -- "Erobert die Burg Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_18 = GetQuestName(2923) -- "Erobert die Burg Königsbanner"

-- Cyrodiil. PvP Quests. Elder Scrolls Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_01 = GetQuestName(2661) -- "Die Alma Ruma-Schriftrolle der Alten"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_02 = GetQuestName(2610) -- "Die Altadoon-Schriftrolle der Alten"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_03 = GetQuestName(2640) -- "Die Chim-Schriftrolle der Alten"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_04 = GetQuestName(2658) -- "Die Ghartok-Schriftrolle der Alten"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_05 = GetQuestName(2656) -- "Die Mnem-Schriftrolle der Alten"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_06 = GetQuestName(2660) -- "Die Ni-Mohk-Schriftrolle der Alten"

-- Reaper's March. Hadran's Caravan Quests
L.SI_DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_01 = GetQuestName(4668) -- "Echsenrennen"
L.SI_DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_02 = GetQuestName(4669) -- "Stachelball"
L.SI_DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_03 = GetQuestName(4670) -- "Die Trollarena"

-- Event Quests. New Life Festival
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_01 = GetQuestName(5845) -- "Burgbardenherausforderung"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_02 = GetQuestName(5855) -- "Fischgunstfestmahl"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_03 = GetQuestName(5837) -- "Lavafußstampfer"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_04 = GetQuestName(5838) -- "Schlammballschlacht"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_05 = GetQuestName(5839) -- "Signalfeuersprint"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_06 = GetQuestName(5811) -- "Der Schneebärensprung"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_07 = GetQuestName(5856) -- "Steinzahnsause"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_08 = GetQuestName(5834) -- "Die Prüfung der Fünfkrallenlist"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_09 = GetQuestName(5852) -- "Die Kriegswaisenreise"

-- Event Quests. Jester's Festival
L.SI_DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_01 = GetQuestName(5937) -- "Königliche Lustbarkeiten"
L.SI_DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_02 = GetQuestName(5931) -- "Ein edler Gast"
L.SI_DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_03 = GetQuestName(5921) -- "Frühlingserwachen"

-- Weekly. Trials
L.SI_DQT_WEEKLY_TRIALS_01 = GetQuestName(5087) -- "Angriff auf die Zitadelle"
L.SI_DQT_WEEKLY_TRIALS_02 = GetQuestName(5894) -- "Die Zukunft schmieden"
L.SI_DQT_WEEKLY_TRIALS_03 = GetQuestName(5352) -- "Hinab in den Schlund"
L.SI_DQT_WEEKLY_TRIALS_04 = GetQuestName(5102) -- "Der Turm der Magierin"
L.SI_DQT_WEEKLY_TRIALS_05 = GetQuestName(5171) -- "Der älteste Geist"
L.SI_DQT_WEEKLY_TRIALS_06 = GetQuestName(6090) -- "Die Gnade der Heiligen"
L.SI_DQT_WEEKLY_TRIALS_07 = GetQuestName(6503) -- "The Fight for Kyne's Aegis"
L.SI_DQT_WEEKLY_TRIALS_08 = GetQuestName(6654) -- "Of Stone and Steam"
L.SI_DQT_WEEKLY_TRIALS_09 = GetQuestName(6353) -- "The Return of Alkosh"
L.SI_DQT_WEEKLY_TRIALS_10 = GetQuestName(6192) -- "Woe of the Welkynars"

-- Northern Elsweyr Defense Force
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_01 = GetQuestName(6318) -- "Dark Souls, Mighty Weapons"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_02 = GetQuestName(6346) -- "Dragon Lore: Icehammer's Vault"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_03 = GetQuestName(6347) -- "Dragon Lore: Shroud Hearth"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_04 = GetQuestName(6345) -- "Dragon Lore: Stormcrag Crypt"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_05 = GetQuestName(6342) -- "Goblin Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_06 = GetQuestName(6344) -- "Lamia Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_07 = GetQuestName(6343) -- "Lurcher Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_08 = GetQuestName(6341) -- "Skeleton Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_09 = GetQuestName(6329) -- "Spider Demonstration"

-- Northern Elsweyr Bounty Quests -- Modified by DarkPhalanx
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_01 = GetQuestName(6381) -- "A Dastardly Duo"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_02 = GetQuestName(6377) -- "Sword of the Serpent"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_03 = GetQuestName(6382) -- "The Senche of Decay"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_04 = GetQuestName(6378) -- "The Traders' Terror"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_05 = GetQuestName(6379) -- "A Waking Nightmare"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_06 = GetQuestName(6380) -- "Another Day, Another Death"

-- Northern Elsweyr Exploratory Quests -- Modified by DarkPhalanx
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_01 = GetQuestName(6356) -- "Dousing the Daedric Flame"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_02 = GetQuestName(6360) -- "Rifling Through Ruins"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_03 = GetQuestName(6361) -- "The Hungry Cat's Favor"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_04 = GetQuestName(6362) -- "The Serpent's Stampede"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_05 = GetQuestName(6363) -- "Tangled Tea Leaves"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_06 = GetQuestName(6359) -- "Wisdom in the Winds"

-- Northern Elsweyr Dragon World Events -- Added by DarkPhalanx
L.SI_DQT_ELSWEYR_QUESTS_DRAGONHUNT_01 = GetQuestName(6384) -- "Dragon Hunt"

-- Southern Elsweyr Bounty Quest -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_01 = GetQuestName(6425) -- "Fletching Fetching"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_02 = GetQuestName(6422) -- "A Rogue and His Rice"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_03 = GetQuestName(6423) -- "Dust Smote"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_04 = GetQuestName(6376) -- "Goutfang Pariah"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_05 = GetQuestName(6421) -- "Helping the Healers"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_06 = GetQuestName(6424) -- "Scholarly Observations"

-- Southern Elsweyr Exploratory Quest - Senchal -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_01 = GetQuestName(6419) -- "Tomes of the Tsaesci"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_02 = GetQuestName(6432) -- "Solace By Candlelight"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_03 = GetQuestName(6436) -- "Lilies for Remembrance"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_04 = GetQuestName(6438) -- "An Answer in Blood"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_05 = GetQuestName(6437) -- "Moonlit Mushrooms"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_06 = GetQuestName(6431) -- "Sourcing the Ensorcelled"

-- Southern Elsweyr Dragon Hunts - Dragonguard Sanctum -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DRAGONHUNT_01 = GetQuestName(6444) -- "Dawn of the Dragonguard"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DRAGONHUNT_02 = GetQuestName(6435) -- "The Dragonguard's Quarry"

-- Southern Elsweyr New Moon Quests - Dragonguard Sanctum -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_07 = GetQuestName(6406) -- "A Lonely Grave"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_08 = GetQuestName(6430) -- "File Under D"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_09 = GetQuestName(6428) -- "Sticks and Bones"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_10 = GetQuestName(6429) -- "Digging Up the Garden"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_11 = GetQuestName(6433) -- "Rude Awakening"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_12 = GetQuestName(6405) -- "Taking Them to Tusk"

-- Western Skyrim Bounty Quests -- Added by DarkPhalanx
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_01 = GetQuestName(6518) -- "Circle of Cheaters"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_02 = GetQuestName(6526) -- "Feasting in the Dark"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_03 = GetQuestName(6509) -- "Lost Along the Shore"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_04 = GetQuestName(6517) -- "Moonlight Kidnapping"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_05 = GetQuestName(6519) -- "Mother of Shadows"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_06 = GetQuestName(6527) -- "Problem Growth"

-- Western Skyrim Exploratory Quests -- Added by DarkPhalanx
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_01 = GetQuestName(6523) -- "Dwemer Disassembly"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_02 = GetQuestName(6520) -- "Precious Bark"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_03 = GetQuestName(6495) -- "The Preservation of Life"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_04 = GetQuestName(6493) -- "The Strength of Giants"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_05 = GetQuestName(6524) -- "Spiritual Release"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_06 = GetQuestName(6494) -- "A Trail Gone Cold"

-- Western Skyrim Harrowstorms -- Added by DarkPhalanx
L.SI_DQT_WESTERN_SKYRIM_QUESTS_HARROWSTORM_01 = GetQuestName(6512) -- "Halt the Harrowstorms"

-- The Reach - Added By DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_01 = GetQuestName(6585) -- "Discarded Treasures"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_02 = GetQuestName(6556) -- "Namira's Perversions"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_03 = GetQuestName(6582) -- "Ruptures in the Reach"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_04 = GetQuestName(6583) -- "The Scholar's Request"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_05 = GetQuestName(6584) -- "Guides to the Deep"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_06 = GetQuestName(6581) -- "Notes of the Void"

-- The Reach Harrowstorms -- Added by DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_HARROWSTORM_01 = GetQuestName(6559) -- "Halt the Harrowstorms"

-- The Reach Exploratory Quests -- Added by DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_DELVE_01 = GetQuestName(6573) -- "Unhatched Menace"
L.SI_DQT_THE_REACH_QUESTS_DELVE_02 = GetQuestName(6557) -- "Wild Talismans"
L.SI_DQT_THE_REACH_QUESTS_DELVE_03 = GetQuestName(6569) -- "What's Hers is Ours"
L.SI_DQT_THE_REACH_QUESTS_DELVE_04 = GetQuestName(6571) -- "Magic Mycology"
L.SI_DQT_THE_REACH_QUESTS_DELVE_05 = GetQuestName(6567) -- "The Tainted Briarheart"
L.SI_DQT_THE_REACH_QUESTS_DELVE_06 = GetQuestName(6572) -- "Strange Contamination"

-- The Reach Ardanir Quests -- Added by DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_01 = GetQuestName(6603) -- "Alone in the Dark"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_02 = GetQuestName(6604) -- "Defenders of the Reach"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_03 = GetQuestName(6600) -- "Remnants of the Deep Folk"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_04 = GetQuestName(6605) -- "The Language of the Night"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_05 = GetQuestName(6602) -- "The Light of Arkthzand"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_06 = GetQuestName(6606) -- "The Lost Shrine"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_07 = GetQuestName(6601) -- "To Burn Away Evil"

-- Blackwood Delve Quests -- Added by DarkPhalanx
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_01 = GetQuestName(6644) -- "A Proper Blessing"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_02 = GetQuestName(6668) -- "Beauty Amid Danger"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_03 = GetQuestName(6674) -- "Breaking the Chain"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_04 = GetQuestName(6673) -- "Conflict of Interest"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_05 = GetQuestName(6675) -- "Insect Savior"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_06 = GetQuestName(6665) -- "Shadow Tactics"

-- Blackwood World Boss Quests -- Added by DarkPhalanx
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_01 = GetQuestName(6651) -- "A Reign of Frogs"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_02 = GetQuestName(6653) -- "Call of the Ruinach"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_03 = GetQuestName(6649) -- "Goblin Research"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_04 = GetQuestName(6645) -- "Legend of the Man-Bull"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_05 = GetQuestName(6650) -- "Rites of the Sul-Xan"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_06 = GetQuestName(6652) -- "The Trophy-Taker"

-- Deadlands World Boss Quests -- Added by g4m3r7ag
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_01 = GetQuestName(6716) -- "Dangerous Business"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_02 = GetQuestName(6720) -- "Retrieval Gone Awry"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_03 = GetQuestName(6718) -- "Unmaker's Hoard"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_04 = GetQuestName(6719) -- "Careless Contamination"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_05 = GetQuestName(6721) -- "A Paralyzing Lesson"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_06 = GetQuestName(6717) -- "The Mind's Eye"

-- Deadlands Delve Quests -- Added by g4m3r7ag
L.SI_DQT_DEADLANDS_QUESTS_DELVE_01 = GetQuestName(6714) -- "Clandestine Communications"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_02 = GetQuestName(6715) -- "A Discreet Pickup"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_03 = GetQuestName(6712) -- "Forgotten Grave Goods"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_04 = GetQuestName(6710) -- "Propaganda Suppressed"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_05 = GetQuestName(6713) -- "Flowers in the Folly"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_06 = GetQuestName(6711) -- "Brandfire Reformatory Relics"

-- High Isle World Boss Quests -- Added by g4m3r7ag
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_01 = GetQuestName(6821) -- "Ascendant Shadows"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_02 = GetQuestName(6803) -- "Avarice of the Eldertide"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_03 = GetQuestName(6807) -- "The Sable Knight"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_04 = GetQuestName(6816) -- "The Serpent Caller"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_05 = GetQuestName(6822) -- "A Special Reagent"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_06 = GetQuestName(6808) -- "Wildhorn's Wrath"

-- High Isle Delve Quests -- Added by g4m3r7ag
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_01 = GetQuestName(6809) -- "Arcane Research"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_02 = GetQuestName(6826) -- "Druidic Research"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_03 = GetQuestName(6805) -- "A Final Peace"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_04 = GetQuestName(6825) -- "Pirate Problems"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_05 = GetQuestName(6818) -- "Prison Problems"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_06 = GetQuestName(6815) -- "Seek and Destroy"

-- High Isle Volcanic Vents Quests -- Added by g4m3r7ag
L.SI_DQT_HIGH_ISLE_QUESTS_VOLCANIC_VENTS_01 = GetQuestName(6812) -- "Venting the Threat"

-- High Isle Tales of Tribute Quests -- Added by g4m3r7ag
L.SI_DQT_TALES_OF_TRIBUTE_QUESTS_01 = GetQuestName(6831) -- "Cards Across the Continent"
L.SI_DQT_TALES_OF_TRIBUTE_QUESTS_02 = GetQuestName(6832) -- "Dueling Tributes"

-- Galen World Boss Quests -- Added by g4m3r7ag
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_01 = GetQuestName(6886) -- "Flower Fancier"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_02 = GetQuestName(6887) -- "Helpful Handbills"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_03 = GetQuestName(6884) -- "Volcanic Virtuoso"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_04 = GetQuestName(6883) -- "Radiant Souvenirs"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_05 = GetQuestName(6888) -- "Marking the Path"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_06 = GetQuestName(6885) -- "Critter Capture"

-- Galen Delve Quests -- Added by g4m3r7ag
L.SI_DQT_GALEN_QUESTS_DELVE_01 = GetQuestName(6878) -- "Sunflower Stamina"
L.SI_DQT_GALEN_QUESTS_DELVE_02 = GetQuestName(6891) -- "Three-Pronged Approach"
L.SI_DQT_GALEN_QUESTS_DELVE_03 = GetQuestName(6881) -- "A Wailing Wood"
L.SI_DQT_GALEN_QUESTS_DELVE_04 = GetQuestName(6890) -- "Recovered Relics"
L.SI_DQT_GALEN_QUESTS_DELVE_05 = GetQuestName(6889) -- "The Moth Study"
L.SI_DQT_GALEN_QUESTS_DELVE_06 = GetQuestName(6892) -- "Shrines on Shaky Ground"

-- Galen Volcanic Vents Quests -- Added by g4m3r7ag
L.SI_DQT_GALEN_QUESTS_VOLCANIC_VENTS_01 = GetQuestName(6901) -- "Imminent Hazard"

for stringId, translation in pairs(L) do
    SafeAddString(_G[stringId], translation, 0)
end
