-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
-- L is a convenience table so we don't have to write ZO_CreateStringId a bunch of times
local L = {}
local lang = 'fr'
local MN = LibMultilingualName

-- Undaunted Pledges. Maj al-Ragath's Pledges
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_01 = GetQuestName(5274) -- "Serment : Cavernes d'Ombre-noire I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_02 = GetQuestName(5275) -- "Serment : Cavernes d'Ombre-noire II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_03 = GetQuestName(5276) -- "Serment : Creuset des aînés I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_04 = GetQuestName(5277) -- "Serment : Creuset des aînés II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_05 = GetQuestName(5247) -- "Serment : Champignonnière I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_06 = GetQuestName(5248) -- "Serment : Champignonnière II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_07 = GetQuestName(5260) -- "Serment : Tressefuseau I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_08 = GetQuestName(5273) -- "Serment : Tressefuseau II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_09 = GetQuestName(5244) -- "Serment : Cachot interdit I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_10 = GetQuestName(5246) -- "Serment : Cachot interdit II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_11 = GetQuestName(5278) -- "Serment : Égouts d'Haltevoie I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_12 = GetQuestName(5282) -- "Serment : Égouts d'Haltevoie II"

-- Undaunted Pledges. Glirion the Redbeard's Pledges
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_01 = GetQuestName(5288) -- "Serment : Arx Corinium"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_02 = GetQuestName(5305) -- "Serment : Havre de Cœurnoir"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_03 = GetQuestName(5306) -- "Serment : Creuset béni I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_04 = GetQuestName(5290) -- "Serment : Cité des cendres I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_05 = GetQuestName(5381) -- "Serment : Cité des cendres II"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_06 = GetQuestName(5283) -- "Serment : Crypte des cœurs I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_07 = GetQuestName(5284) -- "Serment : Crypte des cœurs II"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_08 = GetQuestName(5291) -- "Serment : Donjon d'Affregivre I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_09 = GetQuestName(5307) -- "Serment : Toile de Sélène"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_10 = GetQuestName(5301) -- "Serment : Île des Tempêtes"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_11 = GetQuestName(5309) -- "Serment : Chambres de la folie"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_12 = GetQuestName(5303) -- "Serment : Volenfell"

-- Undaunted Pledges. Urgarlag Chief-bane's Pledges
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_01 = GetQuestName(6053) -- "Serment : Forge de Sangracine"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_02 = GetQuestName(5780) -- "Serment : Berceau des ombres"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_03 = GetQuestName(6054) -- "Serment : Forteresse d'Épervine"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_04 = GetQuestName(6155) -- "Serment : Repaire du croc"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_05 = GetQuestName(5382) -- "Serment : Prison de la cité impériale"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_06 = GetQuestName(6189) -- "Serment : Procession des Sacrifiés"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_07 = GetQuestName(6187) -- "Serment : Fort du Chasseur lunaire"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_08 = GetQuestName(5636) -- "Serment : Ruines de Mazzatun"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_09 = GetQuestName(6154) -- "Serment : Pic de la Mandécailles"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_10 = GetQuestName(5431) -- "Serment : Tour d'or blanc"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_11 = GetQuestName(6250) -- "Pledge: Frostvault"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_12 = GetQuestName(6252) -- "Pledge: Depths of Malatar"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_13 = GetQuestName(6352) -- "Pledge: Lair of Maarselok"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_14 = GetQuestName(6350) -- "Pledge: Moongrave Fane"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_15 = GetQuestName(6415) -- "Pledge: Icereach"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_16 = GetQuestName(6417) -- "Pledge: Unhallowed Grave"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_17 = GetQuestName(6508) -- "Pledge: Castle Thorn"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_18 = GetQuestName(6506) -- "Pledge: Stone Garden"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_19 = GetQuestName(6577) -- "Pledge: Black Drake Villa"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_20 = GetQuestName(6579) -- "Pledge: The Cauldron"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_21 = GetQuestName(6684) -- "Pledge: Red Petal Bastion"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_22 = GetQuestName(6686) -- "Pledge: The Dread Cellar"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_23 = GetQuestName(6741) -- "Pledge: Coral Aerie"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_24 = GetQuestName(6743) -- "Pledge: Shipwright's Regret"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_25 = GetQuestName(6836) -- "Pledge: Earthen Root Enclave"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_26 = GetQuestName(6838) -- "Pledge: Graven Deep"

-- Guild Daily Quests. Fighters Guild Daily Quests
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_01 = GetQuestName(5786) -- "Ancres noires au désert d'Alik'r"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_02 = GetQuestName(5793) -- "Ancres noires à Auridia"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_03 = GetQuestName(5787) -- "Ancres noires à Bangkoraï"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_04 = GetQuestName(5789) -- "Ancres noires à Deshaan"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_05 = GetQuestName(5791) -- "Ancres noires en Estemarche"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_06 = GetQuestName(5833) -- "Ancres noires en Glénumbrie"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_07 = GetQuestName(5794) -- "Ancres noires au bois de Graht"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_08 = GetQuestName(5796) -- "Ancres noires à Prasin"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_09 = GetQuestName(5795) -- "Ancres noires à Malabal Tor"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_10 = GetQuestName(5797) -- "Ancres noires à la marche de la Camarde"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_11 = GetQuestName(5785) -- "Ancres noires à Fendretour"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_12 = GetQuestName(5790) -- "Ancres noires à Fangeombre"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_13 = GetQuestName(5788) -- "Ancres noires aux Éboulis"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_14 = GetQuestName(5784) -- "Ancres noires à Havre-tempête"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_15 = GetQuestName(5792) -- "Ancres noires à la Brèche"

-- Guild Daily Quests. Mages Guild Daily Quests
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_01 = GetQuestName(5814) -- "Folie au désert d'Alik'r"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_02 = GetQuestName(5816) -- "Folie à Auridia"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_03 = GetQuestName(5818) -- "Folie à Bangkoraï"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_04 = GetQuestName(5819) -- "La folie à Deshaan"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_05 = GetQuestName(5820) -- "Folie en Estemarche"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_06 = GetQuestName(5822) -- "Folie en Glénumbrie"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_07 = GetQuestName(5823) -- "Folie au bois de Graht"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_08 = GetQuestName(5824) -- "Folie à Prasin"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_09 = GetQuestName(5825) -- "Folie à Malabal Tor"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_10 = GetQuestName(5826) -- "Folie à la marche de la Camarde"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_11 = GetQuestName(5827) -- "Folie à Fendretour"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_12 = GetQuestName(5828) -- "Folie à Fangeombre"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_13 = GetQuestName(5829) -- "Folie aux Éboulis"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_14 = GetQuestName(5830) -- "La folie d'Havre-tempête"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_15 = GetQuestName(5831) -- "Folie à la Brèche"

-- Guild Daily Quests. Undaunted Daily Quests
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_01 = GetQuestName(5735) -- "Protection des ancêtres à Deshaan"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_02 = GetQuestName(5733) -- "Anciens armements de Bangkoraï"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_03 = GetQuestName(5738) -- "Babioles ayléides au bois de Graht"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_04 = GetQuestName(5853) -- "Justice culinaire à Prasin"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_05 = GetQuestName(5800) -- "Babioles maudites d'Havre-tempête"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_06 = GetQuestName(5808) -- "Les ténèbres éclatent à Fendretour"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_07 = GetQuestName(5737) -- "Reliques dwemers des Éboulis"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_08 = GetQuestName(5778) -- "Donnant, donnant à Fangeombre"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_09 = GetQuestName(5779) -- "Intrigue glacée en Estemarche"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_10 = GetQuestName(5802) -- "Brasiers enflammés de la Brèche"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_11 = GetQuestName(5744) -- "Vol de mascotte à la Marche de la camarde"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_12 = GetQuestName(5745) -- "Perles fondues du désert d'Alik'r"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_13 = GetQuestName(5739) -- "Sac des Freux écarlates en Glénumbrie"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_14 = GetQuestName(5734) -- "Le piège aux esprits de Malabal Tor"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_15 = GetQuestName(5798) -- "Ténèbres voilées à Auridia"

-- Crafting Writs. Consumables Crafting Writs
L.SI_DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_01 = GetQuestName(6105) -- "Alchemist Writ"
L.SI_DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_02 = GetQuestName(5407) -- "Enchanter Writ"
L.SI_DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_03 = GetQuestName(5414) -- "Provisioner Writ"

-- Crafting Writs. Equipment Crafting Writs
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_01 = GetQuestName(5377) -- "Blacksmith Writ"
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_02 = GetQuestName(5374) -- "Clothier Writ"
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_03 = GetQuestName(6228) -- "Jewelry Crafting Writ"
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_04 = GetQuestName(5395) -- "Woodworker Writ"

-- Crafting Writs. Master Writs
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_01 = GetQuestName(5991) -- "A Masterful Concoction"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_02 = GetQuestName(5977) -- "A Masterful Feast"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_03 = GetQuestName(6017) -- "A Masterful Glyph"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_04 = GetQuestName(6022) -- "Masterful Leatherwear"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_05 = GetQuestName(6018) -- "A Masterful Plate"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_06 = GetQuestName(6020) -- "A Masterful Shield"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_07 = GetQuestName(6021) -- "Masterful Tailoring"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_08 = GetQuestName(6452) -- "Masterful Jewelry"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_09 = GetQuestName(5972) -- "A Masterful Weapon"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_10 = GetQuestName(5975) -- "A Masterful Weapon"

-- Craglorn Quests. Lower Craglorn
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_01 = GetQuestName(5756) -- "Critical Mass"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_02 = GetQuestName(5750) -- "The Fallen City of Shada"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_03 = GetQuestName(5762) -- "The Reason We Fight"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_04 = GetQuestName(5749) -- "The Seeker's Archive"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_05 = GetQuestName(5755) -- "Supreme Power"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_06 = GetQuestName(5751) -- "The Trials of Rahni'Za"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_07 = GetQuestName(5754) -- "Waters Run Foul"

-- Craglorn Quests. Upper Craglorn
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_01 = GetQuestName(5767) -- "The Blood of Nirn"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_02 = GetQuestName(5777) -- "The Gray Passage"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_03 = GetQuestName(5766) -- "Iron and Scales"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_04 = GetQuestName(5770) -- "Souls of the Betrayed"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_05 = GetQuestName(5765) -- "Taken Alive"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_06 = GetQuestName(5764) -- "The Truer Fangs"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_07 = GetQuestName(5772) -- "Uncaged"

-- Black Marsh. Cyrodilic Collections
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_01 = GetQuestName(6263) -- "Un goût pour les toxines"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_02 = GetQuestName(6255) -- "Agitation anti-venin"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_03 = GetQuestName(6257) -- "Du balai !"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_04 = GetQuestName(6256) -- "Campagne de recrutement"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_05 = GetQuestName(6260) -- "Viandes salées"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_06 = GetQuestName(6261) -- "Les Vents de Kyne"

-- Imperial City. Imperial City Quests
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_01 = GetQuestName(5500) -- "Dousing the Fires of Industry"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_02 = GetQuestName(5498) -- "Historical Accuracy"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_03 = GetQuestName(5492) -- "The Lifeblood of an Empire"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_04 = GetQuestName(5495) -- "Priceless Treasures"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_05 = GetQuestName(5491) -- "Speaking For The Dead"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_06 = GetQuestName(5501) -- "Watch Your Step"

-- Wrothgar Quests. Delve Dailies
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_01 = GetQuestName(5507) -- "Petit-déjeuner de l'étrange"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_02 = GetQuestName(5505) -- "Incendie au fort"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_03 = GetQuestName(5515) -- "Esprits libres"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_04 = GetQuestName(5514) -- "Plein la panse !"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_05 = GetQuestName(5509) -- "Parties du tout"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_06 = GetQuestName(5504) -- "Commerce de peaux"

-- Wrothgar Quests. Group Boss Dailies
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_01 = GetQuestName(5522) -- "Hérésie par l'ignorance"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_02 = GetQuestName(5518) -- "Nourrir les foules"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_03 = GetQuestName(5521) -- "Abondance de la nature"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_04 = GetQuestName(5524) -- "L'odeur du crime"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_05 = GetQuestName(5519) -- "Sauvetage académique"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_06 = GetQuestName(5523) -- "Neige et vapeur"

-- Thieves Guild Larceny Quests. Guild Jobs
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_01 = GetQuestName(5584) -- "La comtesse avide"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_02 = GetQuestName(5647) -- "Rafle en série"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_03 = GetQuestName(5640) -- "Les mains libres"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_04 = GetQuestName(5642) -- "Doigts agiles"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_05 = GetQuestName(5644) -- "À notre merci"

-- Thieves Guild Larceny Quests. Rye's Reacquisitions
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_01 = GetQuestName(5586) -- "Les perles disparues"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_02 = GetQuestName(5588) -- "Souvenirs d'enfance"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_03 = GetQuestName(5589) -- "La pipe de marin"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_04 = GetQuestName(5587) -- "Crique des esclaves^fd"

-- Thieves Guild Larceny Quests. Heists
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_01 = GetQuestName(5536) -- "Casse : Salles du Sépulcre"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_02 = GetQuestName(5575) -- "Casse : la grotte scintillante"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_03 = GetQuestName(5572) -- "Casse : la Cachette"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_04 = GetQuestName(5577) -- "Casse : égouts reculés"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_05 = GetQuestName(5573) -- "Casse : sépulcre souterrain"

-- Gold Coast Quests. Bounties
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_01 = GetQuestName(5603) -- "Mal enfoui"
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_02 = GetQuestName(5604) -- "Le bien commun"
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_03 = GetQuestName(5605) -- "Ombres menaçantes"
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_04 = GetQuestName(5606) -- "Le hurlement des foules"

-- Gold Coast Quests. Dark Brotherhood Contracts
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_01 = GetQuestName(5627) -- "Contrat : désert d'Alik'r"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_02 = GetQuestName(5693) -- "Contrat : crimes au désert d'Alik'r"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_03 = GetQuestName(5657) -- "Contrat : Auridia"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_04 = GetQuestName(5694) -- "Contrat : crimes à Auridia"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_05 = GetQuestName(5632) -- "Contrat : Bangkoraï"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_06 = GetQuestName(5696) -- "Contrat : crimes à Bangkoraï"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_07 = GetQuestName(5652) -- "Contrat : Deshaan"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_08 = GetQuestName(5698) -- "Contrat : crimes à Deshaan"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_09 = GetQuestName(5670) -- "Contrat : Estemarche"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_10 = GetQuestName(5699) -- "Contrat : crimes en Estemarche"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_11 = GetQuestName(5594) -- "Contrat : Glénumbrie"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_12 = GetQuestName(5700) -- "Contrat : crimes en Glénumbrie"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_13 = GetQuestName(5688) -- "Contrat : crimes de la Côte d'or"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_14 = GetQuestName(5672) -- "Contrat : bois de Graht"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_15 = GetQuestName(5701) -- "Contrat : crimes au bois de Graht"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_16 = GetQuestName(5677) -- "Contrat : Prasin"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_17 = GetQuestName(5703) -- "Contrat : crimes à Prasin"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_18 = GetQuestName(5665) -- "Contrat : Malabal Tor"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_19 = GetQuestName(5704) -- "Contrat : crimes à Malabal Tor"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_20 = GetQuestName(5680) -- "Contrat : marche de la Camarde"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_21 = GetQuestName(5705) -- "Contrat : crimes à la marche de la Camarde"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_22 = GetQuestName(5626) -- "Contrat : Fendretour"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_23 = GetQuestName(5706) -- "Contrat : crimes à Fendretour"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_24 = GetQuestName(5684) -- "Contrat : Fangeombre"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_25 = GetQuestName(5707) -- "Contrat : crimes à Fangeombre"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_26 = GetQuestName(5690) -- "Contrat : Éboulis"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_27 = GetQuestName(5709) -- "Contrat : crimes aux Éboulis"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_28 = GetQuestName(5621) -- "Contrat : Havre-tempête"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_29 = GetQuestName(5710) -- "Contrat : crimes à Havre-tempête"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_30 = GetQuestName(5697) -- "Contrat : la Brèche"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_31 = GetQuestName(5711) -- "Contrat : crimes à la Brèche"

-- Gold Coast Quests. Dark Brotherhood Sacraments
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_01 = GetQuestName(5720) -- "Sacrement : Antre des contrebandiers"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_02 = GetQuestName(5726) -- "Sacrement : Bidonville des égouts"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_03 = GetQuestName(5714) -- "Sacrement : Crique du marchand"

-- Vvardenfell Quests. Bounty
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_01 = GetQuestName(5916) -- "L'Apprenti anxieux"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_02 = GetQuestName(5918) -- "Une faim dévorante"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_03 = GetQuestName(5865) -- "Réduire le troupeau"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_04 = GetQuestName(5866) -- "Garanti sans bœuf"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_05 = GetQuestName(5904) -- "Malédiction de Salothan"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_06 = GetQuestName(5906) -- "Chant de la sirène"

-- Vvardenfell Quests. Exploratory
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_01 = GetQuestName(5956) -- "Perturbations daedriques"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_02 = GetQuestName(5962) -- "L'équation kwama"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_03 = GetQuestName(5961) -- "Plantage à la plantation"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_04 = GetQuestName(5934) -- "Déduction fiscale"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_05 = GetQuestName(5915) -- "Tribus troublées"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_06 = GetQuestName(5958) -- "Mouvement syndical"

-- Vvardenfell Quests. Hunt
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_01 = GetQuestName(5911) -- "Chasse à Gobe-cendre"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_02 = GetQuestName(5907) -- "Chasse au Grand Zexxin"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_03 = GetQuestName(5913) -- "Chasse au Roi Défense-rasoir"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_04 = GetQuestName(5910) -- "Mère Griffe-dentelée"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_05 = GetQuestName(5912) -- "Chasse au vieux piétineur"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_06 = GetQuestName(5908) -- "Chasse de Tarra-Suj"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_07 = GetQuestName(5909) -- "Chasse au sveeth ondulant"

-- Vvardenfell Quests. Relics
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_01 = GetQuestName(5930) -- "Reliques d'Ashalmawia"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_02 = GetQuestName(5927) -- "Reliques d'Ashurnabitashpi"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_03 = GetQuestName(5925) -- "Reliques d'Assarnatamat"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_04 = GetQuestName(5929) -- "Reliques de Dushariran"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_05 = GetQuestName(5928) -- "Reliques d'Ebernanit"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_06 = GetQuestName(5926) -- "Reliques de Maelkashishi"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_07 = GetQuestName(5924) -- "Reliques de Yasammidan"

-- Clockwork City Quests. Bounty
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BOUNTY_01 = GetQuestName(6077) -- "Un si beau plumage"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BOUNTY_02 = GetQuestName(6076) -- "Attirer l'Imparfait"

-- Clockwork City Quests. Exploratory
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_01 = GetQuestName(6088) -- "Changer les filtres"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_02 = GetQuestName(6081) -- "Graisser les ventilateurs"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_03 = GetQuestName(6089) -- "Remplacer les commutateurs"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_04 = GetQuestName(6079) -- "Retour dans les ombres vertes"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_05 = GetQuestName(6080) -- "Une avarie d'ombre"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_06 = GetQuestName(6073) -- "Une ombre égarée"

-- Clockwork City Quests. Tarnished
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_01 = GetQuestName(6042) -- "Pilule amère"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_02 = GetQuestName(6038) -- "Chaque jour sur le métier"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_03 = GetQuestName(6040) -- "La poisse"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_04 = GetQuestName(6041) -- "Accumulation enchantée"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_05 = GetQuestName(6037) -- "Ce qui alimente nos feux"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_06 = GetQuestName(6039) -- "Détails à régler"

-- Clockwork City Quests. Blackfeather Court
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_01 = GetQuestName(6024) -- "Lueur et Chatoiement"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_02 = GetQuestName(6107) -- "Une affaire de loisirs"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_03 = GetQuestName(6072) -- "Une histoire de respect"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_04 = GetQuestName(6106) -- "Une affaire de tributs"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_05 = GetQuestName(6071) -- "Morceaux de choix"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_06 = GetQuestName(6070) -- "Petites bouchées"

-- Summerset Quests. Bounty
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_01 = GetQuestName(6084) -- "L'Alchimiste abyssal"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_02 = GetQuestName(6085) -- "Du même plumage"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_03 = GetQuestName(6086) -- "Inoubliable"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_04 = GetQuestName(6087) -- "Naufragé"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_05 = GetQuestName(6082) -- "La mer maladive"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_06 = GetQuestName(6083) -- "Dompter la nature"

-- Summerset Quests. Exploratory
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_01 = GetQuestName(6159) -- "Abattage de serpents"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_02 = GetQuestName(6152) -- "Fin du pèlerinage"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_03 = GetQuestName(6158) -- "La course aux reliques"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_04 = GetQuestName(6157) -- "La beauté d'une rose"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_05 = GetQuestName(6156) -- "Souffler la lumière"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_06 = GetQuestName(6160) -- "Qu'on oublie jusqu'à leur nom"

-- Summerset Quests. Abyssal Geysers
L.SI_DQT_SUMMERSET_QUESTS_ABYSSAL_GEYSERS_01 = GetQuestName(6202) -- "Le naufrage du Couchant"

-- Murkmire Quests. Bounty
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_01 = GetQuestName(6233) -- "Graves circonstances"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_02 = GetQuestName(6236) -- "Funestes attentes"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_03 = GetQuestName(6237) -- "Mémentos"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_04 = GetQuestName(6235) -- "Vieilles babioles"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_05 = GetQuestName(6238) -- "Vieux ennemis"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_06 = GetQuestName(6234) -- "Vieille croissance"

-- Murkmire Quests. Exploratory
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_01 = GetQuestName(6253) -- "Armure antique"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_02 = GetQuestName(6268) -- "Le silence tombe"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_03 = GetQuestName(6248) -- "Vieux parchemins"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_04 = GetQuestName(6264) -- "Bougies sacrées"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_05 = GetQuestName(6267) -- "Les outils du massacre"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_06 = GetQuestName(6247) -- "Le poids des mots"

-- Murkmire Quests. Root-Whisper
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_01 = GetQuestName(6286) -- "L'aloès qui soigne"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_02 = GetQuestName(6288) -- "Les émissaires qui hésitent"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_03 = GetQuestName(6290) -- "Le cuir qui protège"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_04 = GetQuestName(6287) -- "Les champignons qui nourrissent"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_05 = GetQuestName(6289) -- "Les offrandes qui cachent"

-- Cyrodiil. Cyrodiil Settlement Quests. Bruma
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_01 = GetQuestName(4561) -- "Au plus bas"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_02 = GetQuestName(4563) -- "Capsules de Cappière"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_03 = GetQuestName(4564) -- "Seuls et perdus"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_04 = GetQuestName(4568) -- "Les pierres dressées"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_05 = GetQuestName(4569) -- "Renforts ennemis"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_06 = GetQuestName(4570) -- "Connais ton ennemi"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_07 = GetQuestName(4572) -- "Demande d'aide"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_08 = GetQuestName(4579) -- "Éliminer le magistère"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_09 = GetQuestName(4581) -- "Invisible"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_10 = GetQuestName(4591) -- "Intervention opportune"

-- Cyrodiil. Cyrodiil Settlement Quests. Cheydinhal
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_01 = GetQuestName(4421) -- "Un problème épineux"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_02 = GetQuestName(4422) -- "Épicé"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_03 = GetQuestName(4425) -- "Prisonniers de guerre"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_04 = GetQuestName(4430) -- "Le domaine brûlé"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_05 = GetQuestName(4433) -- "Trésor ayléide"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_06 = GetQuestName(4417) -- "Les eaux souillées"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_07 = GetQuestName(4420) -- "Souvenir"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_08 = GetQuestName(4424) -- "Une dette à échéance"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_09 = GetQuestName(4426) -- "Accumuler les chances"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_10 = GetQuestName(4434) -- "Pour la piété"

-- Cyrodiil. Cyrodiil Settlement Quests. Chorrol and Weynon Priory
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_01 = GetQuestName(4226) -- "Mort aux Dagues noires !"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_02 = GetQuestName(4247) -- "La garde jamais ne se repose"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_03 = GetQuestName(4263) -- "Champ de feu"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_04 = GetQuestName(4265) -- "Le mensonge… à quel prix !"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_05 = GetQuestName(4270) -- "La cachette"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_06 = GetQuestName(4224) -- "Abominations"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_07 = GetQuestName(4228) -- "La griffe d'Akatosh"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_08 = GetQuestName(4238) -- "Livraison tardive"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_09 = GetQuestName(4242) -- "La liche"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_10 = GetQuestName(4244) -- "Les vivres de la Dague noire"

-- Cyrodiil. Cyrodiil Settlement Quests. Cropsford
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_01 = GetQuestName(4505) -- "Graines d'espoir"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_02 = GetQuestName(4507) -- "Offrandes à Zénithar"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_03 = GetQuestName(4509) -- "Le temps des moissons"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_04 = GetQuestName(4512) -- "Les morts de Calárith"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_05 = GetQuestName(4517) -- "Promontoire de la couronne^md"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_06 = GetQuestName(4520) -- "Espions de la Main sanglante !"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_07 = GetQuestName(4522) -- "La propriété Hedoran"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_08 = GetQuestName(4527) -- "Protection des connaissances"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_09 = GetQuestName(4540) -- "La balafre du bois"

-- Cyrodiil. Cyrodiil Settlement Quests. Vlastarus
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_01 = GetQuestName(4048) -- "L'approche directe"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_02 = GetQuestName(4052) -- "Mort à la mégère"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_03 = GetQuestName(4065) -- "Une présence maléfique"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_04 = GetQuestName(4066) -- "La peau de l'ours"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_05 = GetQuestName(4068) -- "Mémentos"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_06 = GetQuestName(4072) -- "Diplomatie rouge"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_07 = GetQuestName(4073) -- "Bannière volée"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_08 = GetQuestName(4074) -- "Pour un ami"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_09 = GetQuestName(4079) -- "Essence de feu"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_10 = GetQuestName(4081) -- "Écailles d'argent"

-- Cyrodiil. Fighters Guild Bounty Quests
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_01 = GetQuestName(4877) -- "Prime : Dagues noires"
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_02 = GetQuestName(4880) -- "Prime : gobelins"
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_03 = GetQuestName(4878) -- "Prime : Vipères grises"
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_04 = GetQuestName(4879) -- "Prime : Chemin d'ombres"

-- Cyrodiil. PvP Quests. Battle Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_01 = GetQuestName(3206) -- "Capturez la ferme d'Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_02 = GetQuestName(3244) -- "Capturez la scierie d'Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_03 = GetQuestName(3262) -- "Capturez la mine d'Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_04 = GetQuestName(3198) -- "Capturez la ferme de Houblon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_05 = GetQuestName(3236) -- "Capturez la scierie de Houblon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_06 = GetQuestName(3254) -- "Capturez la mine de Houblon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_07 = GetQuestName(3201) -- "Capturez la ferme d'Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_08 = GetQuestName(3239) -- "Capturez la scierie d'Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_09 = GetQuestName(3257) -- "Capturez la mine d'Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_10 = GetQuestName(3197) -- "Capturez la ferme de Cendre"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_11 = GetQuestName(3234) -- "Capturez la scierie de Cendre"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_12 = GetQuestName(3253) -- "Capturez la mine de Cendre"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_13 = GetQuestName(3210) -- "Capturez la ferme de Botte-Noire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_14 = GetQuestName(3248) -- "Capturez la scierie de Botte-Noire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_15 = GetQuestName(3268) -- "Capturez la mine de Botte-Noire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_16 = GetQuestName(2970) -- "Capturez la ferme du Crin-de-Sang"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_17 = GetQuestName(3249) -- "Capturez la scierie du Crin-de-Sang"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_18 = GetQuestName(3269) -- "Capturez la mine du Crin-de-Sang"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_19 = GetQuestName(3204) -- "Capturez la ferme de Sente-azur"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_20 = GetQuestName(3242) -- "Capturez la scierie de Sente-azur"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_21 = GetQuestName(3260) -- "Capturez la mine de Sente-azur"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_22 = GetQuestName(3209) -- "Capturez la ferme de Bringée"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_23 = GetQuestName(3247) -- "Capturez la scierie de Bringée"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_24 = GetQuestName(3266) -- "Capturez la mine de Bringée"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_25 = GetQuestName(3200) -- "Capturez la ferme de Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_26 = GetQuestName(3238) -- "Capturez la scierie de Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_27 = GetQuestName(3256) -- "Capturez la mine de Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_28 = GetQuestName(2958) -- "Capturez la ferme de Griffe-dragon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_29 = GetQuestName(3237) -- "Capturez la scierie de Griffe-dragon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_30 = GetQuestName(3255) -- "Capturez la mine de Griffe-dragon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_31 = GetQuestName(3205) -- "Capturez la ferme de Malard"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_32 = GetQuestName(3243) -- "Capturez la scierie de Malard"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_33 = GetQuestName(2944) -- "Capturez la mine de Malard"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_34 = GetQuestName(3207) -- "Capturez la ferme de Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_35 = GetQuestName(3245) -- "Capturez la scierie de Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_36 = GetQuestName(3263) -- "Capturez la mine de Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_37 = GetQuestName(3203) -- "Capturez la ferme de Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_38 = GetQuestName(3241) -- "Capturez la scierie de Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_39 = GetQuestName(3259) -- "Capturez la mine de Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_40 = GetQuestName(3196) -- "Capturez la ferme de Brumeclaire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_41 = GetQuestName(3233) -- "Capturez la scierie de Brumeclaire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_42 = GetQuestName(3252) -- "Capturez la mine de Brumeclaire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_43 = GetQuestName(3202) -- "Capturez la ferme des Armoiries"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_44 = GetQuestName(3240) -- "Capturez la scierie des Armoiries"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_45 = GetQuestName(3258) -- "Capturez la mine des Armoiries"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_46 = GetQuestName(3102) -- "Capturez la ferme de Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_47 = GetQuestName(3140) -- "Capturez la scierie de Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_48 = GetQuestName(3251) -- "Capturez la mine de Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_49 = GetQuestName(3208) -- "Capturez la ferme de Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_50 = GetQuestName(3246) -- "Capturez la scierie de Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_51 = GetQuestName(3265) -- "Capturez la mine de Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_52 = GetQuestName(3194) -- "Capturez la ferme de Bayle"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_53 = GetQuestName(2972) -- "Capturez la scierie de Bayle"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_54 = GetQuestName(3250) -- "Capturez la mine de Bayle"

-- Cyrodiil. PvP Quests. Bounty Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_01 = GetQuestName(5228) -- "Tuez des Chevaliers-dragons ennemis"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_02 = GetQuestName(5231) -- "Tuez des Lames noires ennemis"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_03 = GetQuestName(4349) -- "Tuez les joueurs adverses"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_04 = GetQuestName(5234) -- "Tuez des Sorciers ennemis"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_05 = GetQuestName(5222) -- "Tuez les templiers ennemis"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_06 = GetQuestName(6012) -- "Tuez des gardiens ennemis"

-- Cyrodiil. PvP Quests. Conquest Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_01 = GetQuestName(6207) -- "Capture All 3 Towns"
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_02 = GetQuestName(6208) -- "Capture Any Nine Resources"
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_03 = GetQuestName(6210) -- "Capture All Three Keeps"
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_04 = GetQuestName(6209) -- "Kill 40 Enemy Players"

-- Cyrodiil. PvP Quests. Scouting Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_01 = GetQuestName(2816) -- "Explorez la ferme d'Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_02 = GetQuestName(2893) -- "Explorez la scierie d'Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_03 = GetQuestName(2870) -- "Explorez la mine d'Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_04 = GetQuestName(2808) -- "Explorez la ferme de Houblon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_05 = GetQuestName(2826) -- "Explorez la scierie de Houblon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_06 = GetQuestName(2862) -- "Explorez la mine de Houblon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_07 = GetQuestName(2811) -- "Explorez la ferme d'Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_08 = GetQuestName(2847) -- "Explorez la bastille Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_09 = GetQuestName(2829) -- "Explorez la scierie d'Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_10 = GetQuestName(2865) -- "Explorez la mine d'Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_11 = GetQuestName(2807) -- "Explorez la ferme de Cendre"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_12 = GetQuestName(2825) -- "Explorez la scierie de Cendre"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_13 = GetQuestName(2861) -- "Explorez la mine de Cendre"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_14 = GetQuestName(2820) -- "Explorez la ferme de Botte-noire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_15 = GetQuestName(2838) -- "Explorez la scierie de Botte-noire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_16 = GetQuestName(2802) -- "Explorez la mine de Botte-noire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_17 = GetQuestName(2821) -- "Explorez la ferme du Crin-de-Sang"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_18 = GetQuestName(2839) -- "Explorez la scierie du Crin-de-Sang"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_19 = GetQuestName(2803) -- "Explorez la mine du Crin-de-Sang"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_20 = GetQuestName(2814) -- "Explorez la ferme de Sente-azur"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_21 = GetQuestName(2850) -- "Explorez la bastille de Sente-azur"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_22 = GetQuestName(2832) -- "Explorez la scierie de Sente-azur"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_23 = GetQuestName(2868) -- "Explorez la mine de Sente-azur"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_24 = GetQuestName(2819) -- "Explorez la ferme de Bringée"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_25 = GetQuestName(2837) -- "Explorez la scierie de Bringée"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_26 = GetQuestName(2801) -- "Explorez la mine de Bringée"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_27 = GetQuestName(2852) -- "Explorez le château d'Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_28 = GetQuestName(2856) -- "Explorez le château de Botte-noire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_29 = GetQuestName(2857) -- "Explorez le château Crin-de-Sang"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_30 = GetQuestName(2855) -- "Explorez le château de Bringée"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_31 = GetQuestName(2853) -- "Explorez le château Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_32 = GetQuestName(2854) -- "Explorez le château Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_33 = GetQuestName(2810) -- "Explorez la ferme de Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_34 = GetQuestName(2846) -- "Explorez la bastille Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_35 = GetQuestName(2828) -- "Explorez la scierie de Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_36 = GetQuestName(2864) -- "Explorez la mine de Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_37 = GetQuestName(2809) -- "Explorez la ferme de Griffe-dragon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_38 = GetQuestName(2827) -- "Explorez la scierie de Griffe-dragon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_39 = GetQuestName(2863) -- "Explorez la mine de Griffe-dragon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_40 = GetQuestName(2815) -- "Explorez la ferme de Malard"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_41 = GetQuestName(2851) -- "Explorez la bastille Malard"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_42 = GetQuestName(2833) -- "Explorez la scierie de Malard"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_43 = GetQuestName(2869) -- "Explorez la mine de Malard"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_44 = GetQuestName(2817) -- "Explorez la ferme de Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_45 = GetQuestName(2835) -- "Explorez la scierie de Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_46 = GetQuestName(2871) -- "Explorez la mine de Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_47 = GetQuestName(2813) -- "Explorez la ferme de Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_48 = GetQuestName(2849) -- "Explorez la bastille Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_49 = GetQuestName(2831) -- "Explorez la scierie de Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_50 = GetQuestName(2867) -- "Explorez la mine de Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_51 = GetQuestName(2844) -- "Explorez fort Houblon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_52 = GetQuestName(2843) -- "Explorez fort Cendre"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_53 = GetQuestName(2845) -- "Explorez fort Griffe-dragon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_54 = GetQuestName(2842) -- "Explorez fort Brumeclaire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_55 = GetQuestName(2841) -- "Explorez fort Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_56 = GetQuestName(2840) -- "Explorez fort Bayle"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_57 = GetQuestName(2806) -- "Explorez la ferme de Brumeclaire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_58 = GetQuestName(2824) -- "Explorez la scierie de Brumeclaire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_59 = GetQuestName(2860) -- "Explorez la mine de Brumeclaire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_60 = GetQuestName(2812) -- "Explorez la ferme des Armoiries"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_61 = GetQuestName(2848) -- "Explorez la bastille des Armoiries"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_62 = GetQuestName(2830) -- "Explorez la scierie des Armoiries"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_63 = GetQuestName(2866) -- "Explorez la mine des Armoiries"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_64 = GetQuestName(2805) -- "Explorez la ferme de Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_65 = GetQuestName(2823) -- "Explorez la scierie de Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_66 = GetQuestName(2859) -- "Explorez la mine de Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_67 = GetQuestName(2818) -- "Explorez la ferme de Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_68 = GetQuestName(2836) -- "Explorez la scierie de Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_69 = GetQuestName(2800) -- "Explorez la mine de Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_70 = GetQuestName(2804) -- "Explorez la ferme de Bayle"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_71 = GetQuestName(2822) -- "Explorez la scierie de Bayle"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_72 = GetQuestName(2858) -- "Explorez la mine de Bayle"

-- Cyrodiil. PvP Quests. Warfront Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_01 = GetQuestName(2927) -- "Capturez le château d'Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_02 = GetQuestName(2931) -- "Capturez le château de Botte-Noire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_03 = GetQuestName(2932) -- "Capturez le château Crin-de-Sang"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_04 = GetQuestName(2930) -- "Capturez le château de Bringée"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_05 = GetQuestName(2928) -- "Capturez le château Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_06 = GetQuestName(2929) -- "Capturez le château Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_07 = GetQuestName(2919) -- "Capturez fort Houblon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_08 = GetQuestName(2918) -- "Capturez fort Cendre"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_09 = GetQuestName(2920) -- "Capturez fort Griffe-dragon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_10 = GetQuestName(2917) -- "Capturez fort Brumeclaire"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_11 = GetQuestName(2916) -- "Capturez fort Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_12 = GetQuestName(2915) -- "Capturez fort Bayle"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_13 = GetQuestName(2922) -- "Capturez la bastille Arrius"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_14 = GetQuestName(2925) -- "Capturez la bastille de Sente-azur"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_15 = GetQuestName(2921) -- "Capturez la bastille Chalman"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_16 = GetQuestName(2926) -- "Capturez la bastille Malard"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_17 = GetQuestName(2924) -- "Capturez la bastille de Farragut"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_18 = GetQuestName(2923) -- "Capturez la bastille des Armoiries"

-- Cyrodiil. PvP Quests. Elder Scrolls Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_01 = GetQuestName(2661) -- "Le Parchemin des Anciens d'Alma Ruma"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_02 = GetQuestName(2610) -- "Le Parchemin des Anciens d'Altadoon"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_03 = GetQuestName(2640) -- "Le Parchemin des Anciens de Chim"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_04 = GetQuestName(2658) -- "Le Parchemin des Anciens de Ghartok"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_05 = GetQuestName(2656) -- "Le Parchemin des Anciens de Mnem"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_06 = GetQuestName(2660) -- "Le Parchemin des Anciens de Ni-Mohk"

-- Reaper's March. Hadran's Caravan Quests
L.SI_DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_01 = GetQuestName(4668) -- "Course de lézards"
L.SI_DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_02 = GetQuestName(4669) -- "Sangreballe"
L.SI_DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_03 = GetQuestName(4670) -- "L'arène des trolls"

-- Event Quests. New Life Festival
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_01 = GetQuestName(5845) -- "Le défi de la vie de château"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_02 = GetQuestName(5855) -- "Festin de la Manne poissonneuse"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_03 = GetQuestName(5837) -- "Danser Lave-alse"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_04 = GetQuestName(5838) -- "Boules de boue et bonne humeur"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_05 = GetQuestName(5839) -- "La course des fanaux"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_06 = GetQuestName(5811) -- "Le plongeon de l'ours des neiges"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_07 = GetQuestName(5856) -- "La bringue à Pierrecroc"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_08 = GetQuestName(5834) -- "L'Épreuve de la Ruse à cinq griffes"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_09 = GetQuestName(5852) -- "Le séjour des orphelins de guerre"

-- Event Quests. Jester's Festival
L.SI_DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_01 = GetQuestName(5937) -- "Réjouissances royales"
L.SI_DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_02 = GetQuestName(5931) -- "Un noble invité"
L.SI_DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_03 = GetQuestName(5921) -- "Entrain printannier"

-- Weekly. Trials
L.SI_DQT_WEEKLY_TRIALS_01 = GetQuestName(5087) -- "L'assaut contre la citadelle"
L.SI_DQT_WEEKLY_TRIALS_02 = GetQuestName(5894) -- "Forger le futur"
L.SI_DQT_WEEKLY_TRIALS_03 = GetQuestName(5352) -- "Dans la Gueule de Lorkhaj"
L.SI_DQT_WEEKLY_TRIALS_04 = GetQuestName(5102) -- "La tour du mage"
L.SI_DQT_WEEKLY_TRIALS_05 = GetQuestName(5171) -- "Le fantôme aîné"
L.SI_DQT_WEEKLY_TRIALS_06 = GetQuestName(6090) -- "La Miséricorde des Saints"
L.SI_DQT_WEEKLY_TRIALS_07 = GetQuestName(6503) -- "The Fight for Kyne's Aegis"
L.SI_DQT_WEEKLY_TRIALS_08 = GetQuestName(6654) -- "Of Stone and Steam"
L.SI_DQT_WEEKLY_TRIALS_09 = GetQuestName(6353) -- "The Return of Alkosh"
L.SI_DQT_WEEKLY_TRIALS_10 = GetQuestName(6192) -- "Woe of the Welkynars"

-- Northern Elsweyr Defense Force
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_01 = GetQuestName(6318) -- "Dark Souls, Mighty Weapons"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_02 = GetQuestName(6346) -- "Dragon Lore: Icehammer's Vault"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_03 = GetQuestName(6347) -- "Dragon Lore: Shroud Hearth"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_04 = GetQuestName(6345) -- "Dragon Lore: Stormcrag Crypt"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_05 = GetQuestName(6342) -- "Goblin Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_06 = GetQuestName(6344) -- "Lamia Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_07 = GetQuestName(6343) -- "Lurcher Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_08 = GetQuestName(6341) -- "Skeleton Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_09 = GetQuestName(6329) -- "Spider Demonstration"

-- Northern Elsweyr Bounty Quests -- Modified by DarkPhalanx
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_01 = GetQuestName(6381) -- "A Dastardly Duo"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_02 = GetQuestName(6377) -- "Sword of the Serpent"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_03 = GetQuestName(6382) -- "The Senche of Decay"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_04 = GetQuestName(6378) -- "The Traders' Terror"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_05 = GetQuestName(6379) -- "A Waking Nightmare"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_06 = GetQuestName(6380) -- "Another Day, Another Death"

-- Northern Elsweyr Exploratory Quests -- Modified by DarkPhalanx
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_01 = GetQuestName(6356) -- "Dousing the Daedric Flame"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_02 = GetQuestName(6360) -- "Rifling Through Ruins"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_03 = GetQuestName(6361) -- "The Hungry Cat's Favor"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_04 = GetQuestName(6362) -- "The Serpent's Stampede"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_05 = GetQuestName(6363) -- "Tangled Tea Leaves"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_06 = GetQuestName(6359) -- "Wisdom in the Winds"

-- Northern Elsweyr Dragon World Events -- Added by DarkPhalanx
L.SI_DQT_ELSWEYR_QUESTS_DRAGONHUNT_01 = GetQuestName(6384) -- "Dragon Hunt"

-- Southern Elsweyr Bounty Quest -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_01 = GetQuestName(6425) -- "Fletching Fetching"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_02 = GetQuestName(6422) -- "A Rogue and His Rice"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_03 = GetQuestName(6423) -- "Dust Smote"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_04 = GetQuestName(6376) -- "Goutfang Pariah"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_05 = GetQuestName(6421) -- "Helping the Healers"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_06 = GetQuestName(6424) -- "Scholarly Observations"

-- Southern Elsweyr Exploratory Quest - Senchal -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_01 = GetQuestName(6419) -- "Tomes of the Tsaesci"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_02 = GetQuestName(6432) -- "Solace By Candlelight"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_03 = GetQuestName(6436) -- "Lilies for Remembrance"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_04 = GetQuestName(6438) -- "An Answer in Blood"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_05 = GetQuestName(6437) -- "Moonlit Mushrooms"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_06 = GetQuestName(6431) -- "Sourcing the Ensorcelled"

-- Southern Elsweyr Dragon Hunts - Dragonguard Sanctum -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DRAGONHUNT_01 = GetQuestName(6444) -- "Dawn of the Dragonguard"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DRAGONHUNT_02 = GetQuestName(6435) -- "The Dragonguard's Quarry"

-- Southern Elsweyr New Moon Quests - Dragonguard Sanctum -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_07 = GetQuestName(6406) -- "A Lonely Grave"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_08 = GetQuestName(6430) -- "File Under D"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_09 = GetQuestName(6428) -- "Sticks and Bones"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_10 = GetQuestName(6429) -- "Digging Up the Garden"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_11 = GetQuestName(6433) -- "Rude Awakening"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_12 = GetQuestName(6405) -- "Taking Them to Tusk"

-- Western Skyrim Bounty Quests -- Added by DarkPhalanx
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_01 = GetQuestName(6518) -- "Circle of Cheaters"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_02 = GetQuestName(6526) -- "Feasting in the Dark"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_03 = GetQuestName(6509) -- "Lost Along the Shore"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_04 = GetQuestName(6517) -- "Moonlight Kidnapping"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_05 = GetQuestName(6519) -- "Mother of Shadows"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_06 = GetQuestName(6527) -- "Problem Growth"

-- Western Skyrim Exploratory Quests -- Added by DarkPhalanx
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_01 = GetQuestName(6523) -- "Dwemer Disassembly"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_02 = GetQuestName(6520) -- "Precious Bark"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_03 = GetQuestName(6495) -- "The Preservation of Life"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_04 = GetQuestName(6493) -- "The Strength of Giants"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_05 = GetQuestName(6524) -- "Spiritual Release"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_06 = GetQuestName(6494) -- "A Trail Gone Cold"

-- Western Skyrim Harrowstorms -- Added by DarkPhalanx
L.SI_DQT_WESTERN_SKYRIM_QUESTS_HARROWSTORM_01 = GetQuestName(6512) -- "Halt the Harrowstorms"

-- The Reach - Added By DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_01 = GetQuestName(6585) -- "Discarded Treasures"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_02 = GetQuestName(6556) -- "Namira's Perversions"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_03 = GetQuestName(6582) -- "Ruptures in the Reach"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_04 = GetQuestName(6583) -- "The Scholar's Request"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_05 = GetQuestName(6584) -- "Guides to the Deep"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_06 = GetQuestName(6581) -- "Notes of the Void"

-- The Reach Harrowstorms -- Added by DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_HARROWSTORM_01 = GetQuestName(6559) -- "Halt the Harrowstorms"

-- The Reach Exploratory Quests -- Added by DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_DELVE_01 = GetQuestName(6573) -- "Unhatched Menace"
L.SI_DQT_THE_REACH_QUESTS_DELVE_02 = GetQuestName(6557) -- "Wild Talismans"
L.SI_DQT_THE_REACH_QUESTS_DELVE_03 = GetQuestName(6569) -- "What's Hers is Ours"
L.SI_DQT_THE_REACH_QUESTS_DELVE_04 = GetQuestName(6571) -- "Magic Mycology"
L.SI_DQT_THE_REACH_QUESTS_DELVE_05 = GetQuestName(6567) -- "The Tainted Briarheart"
L.SI_DQT_THE_REACH_QUESTS_DELVE_06 = GetQuestName(6572) -- "Strange Contamination"

-- The Reach Ardanir Quests -- Added by DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_01 = GetQuestName(6603) -- "Alone in the Dark"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_02 = GetQuestName(6604) -- "Defenders of the Reach"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_03 = GetQuestName(6600) -- "Remnants of the Deep Folk"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_04 = GetQuestName(6605) -- "The Language of the Night"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_05 = GetQuestName(6602) -- "The Light of Arkthzand"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_06 = GetQuestName(6606) -- "The Lost Shrine"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_07 = GetQuestName(6601) -- "To Burn Away Evil"

-- Blackwood Delve Quests -- Added by DarkPhalanx
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_01 = GetQuestName(6644) -- "A Proper Blessing"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_02 = GetQuestName(6668) -- "Beauty Amid Danger"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_03 = GetQuestName(6674) -- "Breaking the Chain"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_04 = GetQuestName(6673) -- "Conflict of Interest"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_05 = GetQuestName(6675) -- "Insect Savior"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_06 = GetQuestName(6665) -- "Shadow Tactics"

-- Blackwood World Boss Quests -- Added by DarkPhalanx
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_01 = GetQuestName(6651) -- "A Reign of Frogs"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_02 = GetQuestName(6653) -- "Call of the Ruinach"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_03 = GetQuestName(6649) -- "Goblin Research"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_04 = GetQuestName(6645) -- "Legend of the Man-Bull"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_05 = GetQuestName(6650) -- "Rites of the Sul-Xan"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_06 = GetQuestName(6652) -- "The Trophy-Taker"

-- Deadlands World Boss Quests -- Added by g4m3r7ag
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_01 = GetQuestName(6716) -- "Dangerous Business"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_02 = GetQuestName(6720) -- "Retrieval Gone Awry"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_03 = GetQuestName(6718) -- "Unmaker's Hoard"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_04 = GetQuestName(6719) -- "Careless Contamination"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_05 = GetQuestName(6721) -- "A Paralyzing Lesson"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_06 = GetQuestName(6717) -- "The Mind's Eye"

-- Deadlands Delve Quests -- Added by g4m3r7ag
L.SI_DQT_DEADLANDS_QUESTS_DELVE_01 = GetQuestName(6714) -- "Clandestine Communications"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_02 = GetQuestName(6715) -- "A Discreet Pickup"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_03 = GetQuestName(6712) -- "Forgotten Grave Goods"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_04 = GetQuestName(6710) -- "Propaganda Suppressed"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_05 = GetQuestName(6713) -- "Flowers in the Folly"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_06 = GetQuestName(6711) -- "Brandfire Reformatory Relics"

-- High Isle World Boss Quests -- Added by g4m3r7ag
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_01 = GetQuestName(6821) -- "Ascendant Shadows"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_02 = GetQuestName(6803) -- "Avarice of the Eldertide"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_03 = GetQuestName(6807) -- "The Sable Knight"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_04 = GetQuestName(6816) -- "The Serpent Caller"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_05 = GetQuestName(6822) -- "A Special Reagent"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_06 = GetQuestName(6808) -- "Wildhorn's Wrath"

-- High Isle Delve Quests -- Added by g4m3r7ag
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_01 = GetQuestName(6809) -- "Arcane Research"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_02 = GetQuestName(6826) -- "Druidic Research"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_03 = GetQuestName(6805) -- "A Final Peace"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_04 = GetQuestName(6825) -- "Pirate Problems"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_05 = GetQuestName(6818) -- "Prison Problems"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_06 = GetQuestName(6815) -- "Seek and Destroy"

-- High Isle Volcanic Vents Quests -- Added by g4m3r7ag
L.SI_DQT_HIGH_ISLE_QUESTS_VOLCANIC_VENTS_01 = GetQuestName(6812) -- "Venting the Threat"

-- High Isle Tales of Tribute Quests -- Added by g4m3r7ag
L.SI_DQT_TALES_OF_TRIBUTE_QUESTS_01 = GetQuestName(6831) -- "Cards Across the Continent"
L.SI_DQT_TALES_OF_TRIBUTE_QUESTS_02 = GetQuestName(6832) -- "Dueling Tributes"

-- Galen World Boss Quests -- Added by g4m3r7ag
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_01 = GetQuestName(6886) -- "Flower Fancier"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_02 = GetQuestName(6887) -- "Helpful Handbills"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_03 = GetQuestName(6884) -- "Volcanic Virtuoso"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_04 = GetQuestName(6883) -- "Radiant Souvenirs"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_05 = GetQuestName(6888) -- "Marking the Path"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_06 = GetQuestName(6885) -- "Critter Capture"

-- Galen Delve Quests -- Added by g4m3r7ag
L.SI_DQT_GALEN_QUESTS_DELVE_01 = GetQuestName(6878) -- "Sunflower Stamina"
L.SI_DQT_GALEN_QUESTS_DELVE_02 = GetQuestName(6891) -- "Three-Pronged Approach"
L.SI_DQT_GALEN_QUESTS_DELVE_03 = GetQuestName(6881) -- "A Wailing Wood"
L.SI_DQT_GALEN_QUESTS_DELVE_04 = GetQuestName(6890) -- "Recovered Relics"
L.SI_DQT_GALEN_QUESTS_DELVE_05 = GetQuestName(6889) -- "The Moth Study"
L.SI_DQT_GALEN_QUESTS_DELVE_06 = GetQuestName(6892) -- "Shrines on Shaky Ground"

-- Galen Volcanic Vents Quests -- Added by g4m3r7ag
L.SI_DQT_GALEN_QUESTS_VOLCANIC_VENTS_01 = GetQuestName(6901) -- "Imminent Hazard"

for stringId, translation in pairs(L) do
    SafeAddString(_G[stringId], translation, 0)
end
