-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
-- L is a convenience table so we don't have to write ZO_CreateStringId a bunch of times
local L = {}
local lang = 'ru'
local MN = LibMultilingualName

-- Undaunted Pledges. Maj al-Ragath's Pledges
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_01 = GetQuestName(5274) -- "Обет: пещеры Глубокая тень I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_02 = GetQuestName(5275) -- "Обет: пещеры Глубокая тень II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_03 = GetQuestName(5276) -- "Обет: Элденская лощина I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_04 = GetQuestName(5277) -- "Обет: Элденская лощина II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_05 = GetQuestName(5247) -- "Обет: Грибной грот I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_06 = GetQuestName(5248) -- "Обет: Грибной грот II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_07 = GetQuestName(5260) -- "Обет: Спиндлклатч I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_08 = GetQuestName(5273) -- "Обет: Спиндлклатч II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_09 = GetQuestName(5244) -- "Обет: Темницы изгнанников I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_10 = GetQuestName(5246) -- "Обет: Темницы изгнанников II"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_11 = GetQuestName(5278) -- "Обет: канализация Вэйреста I"
L.SI_DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_12 = GetQuestName(5282) -- "Обет: канализация Вэйреста II"

-- Undaunted Pledges. Glirion the Redbeard's Pledges
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_01 = GetQuestName(5288) -- "Обет: Аркс Кориниум"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_02 = GetQuestName(5305) -- "Обет: гавань Черное Сердце"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_03 = GetQuestName(5306) -- "Обет: Священное Горнило"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_04 = GetQuestName(5290) -- "Обет: Город Пепла I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_05 = GetQuestName(5381) -- "Обет: Город Пепла II"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_06 = GetQuestName(5283) -- "Обет: Крипта Сердец I"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_07 = GetQuestName(5284) -- "Обет: Крипта Сердец II"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_08 = GetQuestName(5291) -- "Обет: крепость Лютых Морозов"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_09 = GetQuestName(5307) -- "Обет: Паутина Селены"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_10 = GetQuestName(5301) -- "Обет: остров Бурь"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_11 = GetQuestName(5309) -- "Обет: Своды Безумия"
L.SI_DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_12 = GetQuestName(5303) -- "Обет: Воленфел"

-- Undaunted Pledges. Urgarlag Chief-bane's Pledges
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_01 = GetQuestName(6053) -- "Обет: кузница Кровавого корня"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_02 = GetQuestName(5780) -- "Обет: Колыбель Теней"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_03 = GetQuestName(6054) -- "Обет: владение Фолкрит"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_04 = GetQuestName(6155) -- "Обет: Логово Клыка"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_05 = GetQuestName(5382) -- "Обет: тюрьма Имперского города"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_06 = GetQuestName(6189) -- "Обет: Путь Жертвоприношений"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_07 = GetQuestName(6187) -- "Обет: крепость Лунного Охотника"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_08 = GetQuestName(5636) -- "Обет: руины Маззатуна"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_09 = GetQuestName(6154) -- "Обет: пик Призывательницы Чешуи"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_10 = GetQuestName(5431) -- "Обет: Башня Белого Золота"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_11 = GetQuestName(6250) -- "Pledge: Frostvault"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_12 = GetQuestName(6252) -- "Pledge: Depths of Malatar"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_13 = GetQuestName(6352) -- "Pledge: Lair of Maarselok"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_14 = GetQuestName(6350) -- "Pledge: Moongrave Fane"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_15 = GetQuestName(6415) -- "Pledge: Icereach"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_16 = GetQuestName(6417) -- "Pledge: Unhallowed Grave"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_17 = GetQuestName(6508) -- "Pledge: Castle Thorn"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_18 = GetQuestName(6506) -- "Pledge: Stone Garden"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_19 = GetQuestName(6577) -- "Pledge: Black Drake Villa"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_20 = GetQuestName(6579) -- "Pledge: The Cauldron"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_21 = GetQuestName(6684) -- "Pledge: Red Petal Bastion"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_22 = GetQuestName(6686) -- "Pledge: The Dread Cellar"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_23 = GetQuestName(6741) -- "Pledge: Coral Aerie"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_24 = GetQuestName(6743) -- "Pledge: Shipwright's Regret"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_25 = GetQuestName(6836) -- "Pledge: Earthen Root Enclave"
L.SI_DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_26 = GetQuestName(6838) -- "Pledge: Graven Deep"

-- Guild Daily Quests. Fighters Guild Daily Quests
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_01 = GetQuestName(5786) -- "Темные якоря в пустыне Алик'р"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_02 = GetQuestName(5793) -- "Темные якоря на Ауридоне"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_03 = GetQuestName(5787) -- "Темные якоря в Бангкорае"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_04 = GetQuestName(5789) -- "Темные якоря в Дешаане"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_05 = GetQuestName(5791) -- "Темные якоря в Истмарке"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_06 = GetQuestName(5833) -- "Темные якоря в Гленумбре"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_07 = GetQuestName(5794) -- "Темные якоря в Гратвуде"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_08 = GetQuestName(5796) -- "Темные якоря в Гриншейде"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_09 = GetQuestName(5795) -- "Темные якоря в Малабал Торе"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_10 = GetQuestName(5797) -- "Темные якоря в Марке Смерти"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_11 = GetQuestName(5785) -- "Темные якоря в Ривенспайре"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_12 = GetQuestName(5790) -- "Темные якоря в Шедоуфене"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_13 = GetQuestName(5788) -- "Темные якоря в Стоунфолзе"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_14 = GetQuestName(5784) -- "Темные якоря в Стормхейвене"
L.SI_DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_15 = GetQuestName(5792) -- "Темные якоря в Рифте"

-- Guild Daily Quests. Mages Guild Daily Quests
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_01 = GetQuestName(5814) -- "Безумие в пустыне Алик'р"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_02 = GetQuestName(5816) -- "Безумие на Ауридоне"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_03 = GetQuestName(5818) -- "Безумие в Бангкорае"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_04 = GetQuestName(5819) -- "Безумие в Дешаане"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_05 = GetQuestName(5820) -- "Безумие в Истмарке"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_06 = GetQuestName(5822) -- "Безумие в Гленумбре"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_07 = GetQuestName(5823) -- "Безумие в Гратвуде"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_08 = GetQuestName(5824) -- "Безумие в Гриншейде"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_09 = GetQuestName(5825) -- "Безумие в Малабал Торе"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_10 = GetQuestName(5826) -- "Безумие в Марке Смерти"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_11 = GetQuestName(5827) -- "Безумие в Ривенспайре"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_12 = GetQuestName(5828) -- "Безумие в Шедоуфене"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_13 = GetQuestName(5829) -- "Безумие в Стоунфолзе"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_14 = GetQuestName(5830) -- "Безумие в Стормхейвене"
L.SI_DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_15 = GetQuestName(5831) -- "Безумие в Рифте"

-- Guild Daily Quests. Undaunted Daily Quests
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_01 = GetQuestName(5735) -- "Обереги предков в Дешаане"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_02 = GetQuestName(5733) -- "Древнее оружие Бангкорая"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_03 = GetQuestName(5738) -- "Айлейдские безделушки в Гратвуде"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_04 = GetQuestName(5853) -- "Кулинарное правосудие в Гриншейде"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_05 = GetQuestName(5800) -- "Проклятые безделушки Стормхейвена"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_06 = GetQuestName(5808) -- "Расцвет тьмы в Ривенспайре"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_07 = GetQuestName(5737) -- "Двемерские реликвии Стоунфолза"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_08 = GetQuestName(5778) -- "Обмен в Шедоуфене"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_09 = GetQuestName(5779) -- "Ледяная интрига в Истмарке"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_10 = GetQuestName(5802) -- "Зажженные погребальные огни в Рифте"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_11 = GetQuestName(5744) -- "Талисман вора в Марке Смерти"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_12 = GetQuestName(5745) -- "Расплавленный жемчуг в пустыне Алик'р"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_13 = GetQuestName(5739) -- "Ограбление Красных Грачей в Гленумбре"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_14 = GetQuestName(5734) -- "The Spirit Trap in Malabal Tor"
L.SI_DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_15 = GetQuestName(5798) -- "Скрытая тьма на Ауридоне"

-- Crafting Writs. Consumables Crafting Writs
L.SI_DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_01 = GetQuestName(6105) -- "Alchemist Writ"
L.SI_DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_02 = GetQuestName(5407) -- "Enchanter Writ"
L.SI_DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_03 = GetQuestName(5414) -- "Provisioner Writ"

-- Crafting Writs. Equipment Crafting Writs
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_01 = GetQuestName(5377) -- "Blacksmith Writ"
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_02 = GetQuestName(5374) -- "Clothier Writ"
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_03 = GetQuestName(6228) -- "Jewelry Crafting Writ"
L.SI_DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_04 = GetQuestName(5395) -- "Woodworker Writ"

-- Crafting Writs. Master Writs
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_01 = GetQuestName(5991) -- "A Masterful Concoction"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_02 = GetQuestName(5977) -- "A Masterful Feast"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_03 = GetQuestName(6017) -- "A Masterful Glyph"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_04 = GetQuestName(6022) -- "Masterful Leatherwear"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_05 = GetQuestName(6018) -- "A Masterful Plate"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_06 = GetQuestName(6020) -- "A Masterful Shield"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_07 = GetQuestName(6021) -- "Masterful Tailoring"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_08 = GetQuestName(6452) -- "Masterful Jewelry"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_09 = GetQuestName(5972) -- "A Masterful Weapon"
L.SI_DQT_CRAFTING_WRITS_MASTER_WRITS_10 = GetQuestName(5975) -- "A Masterful Weapon"

-- Craglorn Quests. Lower Craglorn
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_01 = GetQuestName(5756) -- "Critical Mass"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_02 = GetQuestName(5750) -- "The Fallen City of Shada"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_03 = GetQuestName(5762) -- "The Reason We Fight"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_04 = GetQuestName(5749) -- "The Seeker's Archive"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_05 = GetQuestName(5755) -- "Supreme Power"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_06 = GetQuestName(5751) -- "The Trials of Rahni'Za"
L.SI_DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_07 = GetQuestName(5754) -- "Waters Run Foul"

-- Craglorn Quests. Upper Craglorn
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_01 = GetQuestName(5767) -- "The Blood of Nirn"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_02 = GetQuestName(5777) -- "The Gray Passage"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_03 = GetQuestName(5766) -- "Iron and Scales"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_04 = GetQuestName(5770) -- "Souls of the Betrayed"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_05 = GetQuestName(5765) -- "Taken Alive"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_06 = GetQuestName(5764) -- "The Truer Fangs"
L.SI_DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_07 = GetQuestName(5772) -- "Uncaged"

-- Black Marsh. Cyrodilic Collections
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_01 = GetQuestName(6263) -- "Вкус к отраве"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_02 = GetQuestName(6255) -- "Смешивание противоядия"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_03 = GetQuestName(6257) -- "Бой жукам"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_04 = GetQuestName(6256) -- "Привлечение новых участников"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_05 = GetQuestName(6260) -- "Солонина"
L.SI_DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_06 = GetQuestName(6261) -- "Ветра Кин"

-- Imperial City. Imperial City Quests
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_01 = GetQuestName(5500) -- "Dousing the Fires of Industry"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_02 = GetQuestName(5498) -- "Historical Accuracy"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_03 = GetQuestName(5492) -- "The Lifeblood of an Empire"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_04 = GetQuestName(5495) -- "Priceless Treasures"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_05 = GetQuestName(5491) -- "Speaking For The Dead"
L.SI_DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_06 = GetQuestName(5501) -- "Watch Your Step"

-- Wrothgar Quests. Delve Dailies
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_01 = GetQuestName(5507) -- "Завтрак чудака"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_02 = GetQuestName(5505) -- "Пожар во владении"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_03 = GetQuestName(5515) -- "Свободные духи"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_04 = GetQuestName(5514) -- "До отвала"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_05 = GetQuestName(5509) -- "Части целого"
L.SI_DQT_WROTHGAR_QUESTS_DELVE_DAILIES_06 = GetQuestName(5504) -- "Торговля кожей"

-- Wrothgar Quests. Group Boss Dailies
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_01 = GetQuestName(5522) -- "Ересь невежества"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_02 = GetQuestName(5518) -- "Мясо в массы"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_03 = GetQuestName(5521) -- "Щедрость природы"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_04 = GetQuestName(5524) -- "Запах нечестной игры"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_05 = GetQuestName(5519) -- "Спасение во имя знаний"
L.SI_DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_06 = GetQuestName(5523) -- "Снег и пар"

-- Thieves Guild Larceny Quests. Guild Jobs
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_01 = GetQuestName(5584) -- "The Covetous Countess"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_02 = GetQuestName(5647) -- "Серия преступлений"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_03 = GetQuestName(5640) -- "Руки без дела"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_04 = GetQuestName(5642) -- "Plucking Fingers"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_05 = GetQuestName(5644) -- "Всецело у нас в руках"

-- Thieves Guild Larceny Quests. Rye's Reacquisitions
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_01 = GetQuestName(5586) -- "Потерянные жемчужины"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_02 = GetQuestName(5588) -- "Воспоминания о молодости"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_03 = GetQuestName(5589) -- "Трубка моряка"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_04 = GetQuestName(5587) -- "бухта Рабов"

-- Thieves Guild Larceny Quests. Heists
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_01 = GetQuestName(5536) -- "Ограбление: залы Мертвой лощины"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_02 = GetQuestName(5575) -- "Ограбление: Сверкающий грот"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_03 = GetQuestName(5572) -- "Ограбление: укрытие"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_04 = GetQuestName(5577) -- "Ограбление: Потайные коллекторы"
L.SI_DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_05 = GetQuestName(5573) -- "Ограбление: подземная усыпальница"

-- Gold Coast Quests. Bounties
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_01 = GetQuestName(5603) -- "Захороненное зло"
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_02 = GetQuestName(5604) -- "Всеобщее благо"
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_03 = GetQuestName(5605) -- "Надвигающиеся тени"
L.SI_DQT_GOLD_COAST_QUESTS_BOUNTIES_04 = GetQuestName(5606) -- "Рев толпы"

-- Gold Coast Quests. Dark Brotherhood Contracts
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_01 = GetQuestName(5627) -- "Контракт: пустыня Алик'р"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_02 = GetQuestName(5693) -- "Контракт на серию убийств: пустыня Алик'р"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_03 = GetQuestName(5657) -- "Контракт: Ауридон"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_04 = GetQuestName(5694) -- "Контракт на серию убийств: Ауридон"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_05 = GetQuestName(5632) -- "Контракт: Бангкорай"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_06 = GetQuestName(5696) -- "Контракт на серию убийств: Бангкорай"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_07 = GetQuestName(5652) -- "Контракт: Дешаан"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_08 = GetQuestName(5698) -- "Контракт на серию убийств: Дешаан"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_09 = GetQuestName(5670) -- "Контракт: Истмарк"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_10 = GetQuestName(5699) -- "Контракт на серию убийств: Истмарк"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_11 = GetQuestName(5594) -- "Контракт: Гленумбра"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_12 = GetQuestName(5700) -- "Контракт на серию убийств: Гленумбра"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_13 = GetQuestName(5688) -- "Контракт на серию убийств: Золотой берег"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_14 = GetQuestName(5672) -- "Контракт: Гратвуд"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_15 = GetQuestName(5701) -- "Контракт на серию убийств: Гратвуд"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_16 = GetQuestName(5677) -- "Контракт: Гриншейд"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_17 = GetQuestName(5703) -- "Контракт на серию убийств: Гриншейд"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_18 = GetQuestName(5665) -- "Контракт: Малабал Тор"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_19 = GetQuestName(5704) -- "Контракт на серию убийств: Малабал Тор"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_20 = GetQuestName(5680) -- "Контракт: Марка Смерти"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_21 = GetQuestName(5705) -- "Контракт на серию убийств: Марка Смерти"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_22 = GetQuestName(5626) -- "Контракт: Ривенспайр"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_23 = GetQuestName(5706) -- "Контракт на серию убийств: Ривенспайр"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_24 = GetQuestName(5684) -- "Контракт: Шедоуфен"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_25 = GetQuestName(5707) -- "Контракт на серию убийств: Шедоуфен"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_26 = GetQuestName(5690) -- "Контракт: Стоунфолз"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_27 = GetQuestName(5709) -- "Контракт на серию убийств: Стоунфолз"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_28 = GetQuestName(5621) -- "Контракт: Стормхейвен"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_29 = GetQuestName(5710) -- "Контракт на серию убийств: Стормхейвен"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_30 = GetQuestName(5697) -- "Контракт: Рифт"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_31 = GetQuestName(5711) -- "Контракт на серию убийств: Рифт"

-- Gold Coast Quests. Dark Brotherhood Sacraments
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_01 = GetQuestName(5720) -- "Таинство: логово контрабандистов"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_02 = GetQuestName(5726) -- "Таинство: жилая канализация"
L.SI_DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_03 = GetQuestName(5714) -- "Таинство: пещера торговцев"

-- Vvardenfell Quests. Bounty
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_01 = GetQuestName(5916) -- "Обеспокоенная ученица"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_02 = GetQuestName(5918) -- "Затаившийся алчущий"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_03 = GetQuestName(5865) -- "Отбраковка колонии"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_04 = GetQuestName(5866) -- "Волам здесь не место"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_05 = GetQuestName(5904) -- "Проклятье Салотанов"
L.SI_DQT_VVARDENFELL_QUESTS_BOUNTY_06 = GetQuestName(5906) -- "Песня сирены"

-- Vvardenfell Quests. Exploratory
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_01 = GetQuestName(5956) -- "Даэдрический срыв"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_02 = GetQuestName(5962) -- "Задачка с квама"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_03 = GetQuestName(5961) -- "Насаждение дезинформации"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_04 = GetQuestName(5934) -- "Налоговый вычет"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_05 = GetQuestName(5915) -- "Проблемы племени"
L.SI_DQT_VVARDENFELL_QUESTS_EXPLORATORY_06 = GetQuestName(5958) -- "Беспокойный синдикат"

-- Vvardenfell Quests. Hunt
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_01 = GetQuestName(5911) -- "Охота на Пеплоеда"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_02 = GetQuestName(5907) -- "Охота на Великого Зексина"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_03 = GetQuestName(5913) -- "Охота на Короля Острый Клык"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_04 = GetQuestName(5910) -- "Охота на Мать Зазубренная Клешня"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_05 = GetQuestName(5912) -- "Охота на Старого Топотуна"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_06 = GetQuestName(5908) -- "Охота на Тарра-Судж"
L.SI_DQT_VVARDENFELL_QUESTS_HUNT_07 = GetQuestName(5909) -- "Охота на Извивающегося Свита"

-- Vvardenfell Quests. Relics
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_01 = GetQuestName(5930) -- "Реликвии Ашалмавии"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_02 = GetQuestName(5927) -- "Реликвии Ассурнабиташпи"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_03 = GetQuestName(5925) -- "Реликвии Ассарнатамата"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_04 = GetQuestName(5929) -- "Реликвии Душарирана"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_05 = GetQuestName(5928) -- "Реликвии Эбернанита"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_06 = GetQuestName(5926) -- "Реликвии Мелкашиши"
L.SI_DQT_VVARDENFELL_QUESTS_RELICS_07 = GetQuestName(5924) -- "Реликвии Ясаммидана"

-- Clockwork City Quests. Bounty
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BOUNTY_01 = GetQuestName(6077) -- "Враг в прекрасном оперении"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BOUNTY_02 = GetQuestName(6076) -- "Пробуждение Несовершенства"

-- Clockwork City Quests. Exploratory
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_01 = GetQuestName(6088) -- "Замена фильтров"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_02 = GetQuestName(6081) -- "Смазывание вентиляторов"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_03 = GetQuestName(6089) -- "Замена преобразователей"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_04 = GetQuestName(6079) -- "Обратно в тень"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_05 = GetQuestName(6080) -- "Сумрачная неисправность"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_06 = GetQuestName(6073) -- "Пропавшая тень"

-- Clockwork City Quests. Tarnished
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_01 = GetQuestName(6042) -- "Горькая пилюля"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_02 = GetQuestName(6038) -- "Ежедневная молотилка"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_03 = GetQuestName(6040) -- "Липкое решение"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_04 = GetQuestName(6041) -- "Сбор зачарований"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_05 = GetQuestName(6037) -- "Масло в огонь"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_06 = GetQuestName(6039) -- "Свободные нити"

-- Clockwork City Quests. Blackfeather Court
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_01 = GetQuestName(6024) -- "Шик и блеск"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_02 = GetQuestName(6107) -- "Вопрос о свободном времени"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_03 = GetQuestName(6072) -- "Вопрос уважения"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_04 = GetQuestName(6106) -- "Вопрос о подношениях"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_05 = GetQuestName(6071) -- "Лакомые кусочки"
L.SI_DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_06 = GetQuestName(6070) -- "Кусочки и частички"

-- Summerset Quests. Bounty
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_01 = GetQuestName(6084) -- "Глубинный алхимик"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_02 = GetQuestName(6085) -- "Одного поля ягода"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_03 = GetQuestName(6086) -- "Вечная память"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_04 = GetQuestName(6087) -- "На мели"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_05 = GetQuestName(6082) -- "Болезнь моря"
L.SI_DQT_SUMMERSET_QUESTS_BOUNTY_06 = GetQuestName(6083) -- "Укрощение дикой природы"

-- Summerset Quests. Exploratory
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_01 = GetQuestName(6159) -- "Сокращение популяции змей"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_02 = GetQuestName(6152) -- "Завершение паломничества"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_03 = GetQuestName(6158) -- "Волокита с реликвиями"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_04 = GetQuestName(6157) -- "Красота розы"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_05 = GetQuestName(6156) -- "Тушение пламени"
L.SI_DQT_SUMMERSET_QUESTS_EXPLORATORY_06 = GetQuestName(6160) -- "Вычеркнуть из памяти"

-- Summerset Quests. Abyssal Geysers
L.SI_DQT_SUMMERSET_QUESTS_ABYSSAL_GEYSERS_01 = GetQuestName(6202) -- "Затопление Саммерсета"

-- Murkmire Quests. Bounty
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_01 = GetQuestName(6233) -- "Grave Circumstances"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_02 = GetQuestName(6236) -- "Grave Expectations"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_03 = GetQuestName(6237) -- "Grave Mementos"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_04 = GetQuestName(6235) -- "Old Baubles"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_05 = GetQuestName(6238) -- "Old Enemies"
L.SI_DQT_MURKMIRE_QUESTS_BOUNTY_06 = GetQuestName(6234) -- "Old Growth"

-- Murkmire Quests. Exploratory
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_01 = GetQuestName(6253) -- "Antique Armor"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_02 = GetQuestName(6268) -- "Grave Subject Matter"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_03 = GetQuestName(6248) -- "Old Scrolls"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_04 = GetQuestName(6264) -- "Sacred Candles"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_05 = GetQuestName(6267) -- "Tools of Slaughter"
L.SI_DQT_MURKMIRE_QUESTS_EXPLORATORY_06 = GetQuestName(6247) -- "The Weight of Words"

-- Murkmire Quests. Root-Whisper
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_01 = GetQuestName(6286) -- "Aloe That Heals"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_02 = GetQuestName(6288) -- "Envoys Who Cower"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_03 = GetQuestName(6290) -- "Leather That Protects"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_04 = GetQuestName(6287) -- "Mushrooms That Nourish"
L.SI_DQT_MURKMIRE_QUESTS_ROOT_WHISPER_05 = GetQuestName(6289) -- "Offerings That Hide"

-- Cyrodiil. Cyrodiil Settlement Quests. Bruma
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_01 = GetQuestName(4561) -- "Dangerously Low"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_02 = GetQuestName(4563) -- "Шляпки Замкового Камня"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_03 = GetQuestName(4564) -- "Потерявшиеся и одинокие"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_04 = GetQuestName(4568) -- "Стоячие камни"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_05 = GetQuestName(4569) -- "Enemy Reinforcements"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_06 = GetQuestName(4570) -- "Know thy Enemy"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_07 = GetQuestName(4572) -- "Просьбы о помощи"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_08 = GetQuestName(4579) -- "Bring Down the Magister"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_09 = GetQuestName(4581) -- "Невидимое"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_10 = GetQuestName(4591) -- "Timely Intervention"

-- Cyrodiil. Cyrodiil Settlement Quests. Cheydinhal
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_01 = GetQuestName(4421) -- "Thorns in Our Side"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_02 = GetQuestName(4422) -- "Spice"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_03 = GetQuestName(4425) -- "Пленники войны"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_04 = GetQuestName(4430) -- "Сгоревшее поместье"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_05 = GetQuestName(4433) -- "Сокровище айлейдов"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_06 = GetQuestName(4417) -- "Bloodied Waters"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_07 = GetQuestName(4420) -- "Keepsake"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_08 = GetQuestName(4424) -- "A Debt Come Due"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_09 = GetQuestName(4426) -- "Увеличивая шансы"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_10 = GetQuestName(4434) -- "For Piety's Sake"

-- Cyrodiil. Cyrodiil Settlement Quests. Chorrol and Weynon Priory
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_01 = GetQuestName(4226) -- "Смерть Черным Кинжалам!"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_02 = GetQuestName(4247) -- "Guard Work is Never Done"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_03 = GetQuestName(4263) -- "Огненное поле"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_04 = GetQuestName(4265) -- "Ложь обходится дорого"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_05 = GetQuestName(4270) -- "The Cache"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_06 = GetQuestName(4224) -- "Мерзости"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_07 = GetQuestName(4228) -- "Claw of Akatosh"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_08 = GetQuestName(4238) -- "Просроченные припасы"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_09 = GetQuestName(4242) -- "Лич"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_10 = GetQuestName(4244) -- "Припасы Черных Кинжалов"

-- Cyrodiil. Cyrodiil Settlement Quests. Cropsford
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_01 = GetQuestName(4505) -- "Семена надежды"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_02 = GetQuestName(4507) -- "Подношение Зенитару"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_03 = GetQuestName(4509) -- "Время урожая"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_04 = GetQuestName(4512) -- "The Dead of Culotte"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_05 = GetQuestName(4517) -- "Коронный дозор"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_06 = GetQuestName(4520) -- "Bloody Hand Spies!"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_07 = GetQuestName(4522) -- "Поместье Хедоран"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_08 = GetQuestName(4527) -- "Забота о знаниях"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_09 = GetQuestName(4540) -- "Timberscar Troubles"

-- Cyrodiil. Cyrodiil Settlement Quests. Vlastarus
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_01 = GetQuestName(4048) -- "The Direct Approach"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_02 = GetQuestName(4052) -- "Death to the Crone"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_03 = GetQuestName(4065) -- "An Evil Presence"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_04 = GetQuestName(4066) -- "Bear Essentials"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_05 = GetQuestName(4068) -- "Mementos"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_06 = GetQuestName(4072) -- "Rock Bone Diplomacy"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_07 = GetQuestName(4073) -- "Украденное знамя"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_08 = GetQuestName(4074) -- "For a Friend"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_09 = GetQuestName(4079) -- "Essence of Flame"
L.SI_DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_10 = GetQuestName(4081) -- "Серебряные чешуйки"

-- Cyrodiil. Fighters Guild Bounty Quests
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_01 = GetQuestName(4877) -- "Bounty: Black Daggers"
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_02 = GetQuestName(4880) -- "Bounty: Goblins"
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_03 = GetQuestName(4878) -- "Bounty: Gray Vipers"
L.SI_DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_04 = GetQuestName(4879) -- "Bounty: Shadowed Path"

-- Cyrodiil. PvP Quests. Battle Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_01 = GetQuestName(3206) -- "Capture Alessia Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_02 = GetQuestName(3244) -- "Capture Alessia Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_03 = GetQuestName(3262) -- "Capture Alessia Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_04 = GetQuestName(3198) -- "Capture Aleswell Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_05 = GetQuestName(3236) -- "Capture Aleswell Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_06 = GetQuestName(3254) -- "Capture Aleswell Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_07 = GetQuestName(3201) -- "Capture Arrius Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_08 = GetQuestName(3239) -- "Capture Arrius Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_09 = GetQuestName(3257) -- "Capture Arrius Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_10 = GetQuestName(3197) -- "Capture Ash Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_11 = GetQuestName(3234) -- "Capture Ash Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_12 = GetQuestName(3253) -- "Capture Ash Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_13 = GetQuestName(3210) -- "Capture Black Boot Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_14 = GetQuestName(3248) -- "Capture Black Boot Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_15 = GetQuestName(3268) -- "Capture Black Boot Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_16 = GetQuestName(2970) -- "Capture Bloodmayne Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_17 = GetQuestName(3249) -- "Capture Bloodmayne Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_18 = GetQuestName(3269) -- "Capture Bloodmayne Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_19 = GetQuestName(3204) -- "Capture Blue Road Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_20 = GetQuestName(3242) -- "Capture Blue Road Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_21 = GetQuestName(3260) -- "Capture Blue Road Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_22 = GetQuestName(3209) -- "Capture Brindle Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_23 = GetQuestName(3247) -- "Capture Brindle Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_24 = GetQuestName(3266) -- "Capture Brindle Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_25 = GetQuestName(3200) -- "Capture Chalman Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_26 = GetQuestName(3238) -- "Capture Chalman Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_27 = GetQuestName(3256) -- "Capture Chalman Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_28 = GetQuestName(2958) -- "Capture Dragonclaw Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_29 = GetQuestName(3237) -- "Capture Dragonclaw Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_30 = GetQuestName(3255) -- "Capture Dragonclaw Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_31 = GetQuestName(3205) -- "Capture Drakelowe Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_32 = GetQuestName(3243) -- "Capture Drakelowe Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_33 = GetQuestName(2944) -- "Capture Drakelowe Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_34 = GetQuestName(3207) -- "Capture Faregyl Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_35 = GetQuestName(3245) -- "Capture Faregyl Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_36 = GetQuestName(3263) -- "Capture Faregyl Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_37 = GetQuestName(3203) -- "Capture Farragut Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_38 = GetQuestName(3241) -- "Capture Farragut Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_39 = GetQuestName(3259) -- "Capture Farragut Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_40 = GetQuestName(3196) -- "Capture Glademist Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_41 = GetQuestName(3233) -- "Capture Glademist Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_42 = GetQuestName(3252) -- "Capture Glademist Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_43 = GetQuestName(3202) -- "Capture Kingscrest Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_44 = GetQuestName(3240) -- "Capture Kingscrest Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_45 = GetQuestName(3258) -- "Capture Kingscrest Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_46 = GetQuestName(3102) -- "Capture Rayles Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_47 = GetQuestName(3140) -- "Capture Rayles Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_48 = GetQuestName(3251) -- "Capture Rayles Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_49 = GetQuestName(3208) -- "Capture Roebeck Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_50 = GetQuestName(3246) -- "Capture Roebeck Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_51 = GetQuestName(3265) -- "Capture Roebeck Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_52 = GetQuestName(3194) -- "Capture Warden Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_53 = GetQuestName(2972) -- "Capture Warden Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_54 = GetQuestName(3250) -- "Capture Warden Mine"

-- Cyrodiil. PvP Quests. Bounty Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_01 = GetQuestName(5228) -- "Убить вражеских рыцарей-драконов"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_02 = GetQuestName(5231) -- "Убить вражеских клинков ночи"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_03 = GetQuestName(4349) -- "Kill Enemy Players"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_04 = GetQuestName(5234) -- "Убить вражеских чародеев"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_05 = GetQuestName(5222) -- "Убить вражеских храмовников"
L.SI_DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_06 = GetQuestName(6012) -- "Убить вражеских хранителей"

-- Cyrodiil. PvP Quests. Conquest Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_01 = GetQuestName(6207) -- "Capture All 3 Towns"
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_02 = GetQuestName(6208) -- "Capture Any Nine Resources"
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_03 = GetQuestName(6210) -- "Capture All Three Keeps"
L.SI_DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_04 = GetQuestName(6209) -- "Kill 40 Enemy Players"

-- Cyrodiil. PvP Quests. Scouting Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_01 = GetQuestName(2816) -- "Scout Alessia Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_02 = GetQuestName(2893) -- "Scout Alessia Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_03 = GetQuestName(2870) -- "Scout Alessia Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_04 = GetQuestName(2808) -- "Scout Aleswell Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_05 = GetQuestName(2826) -- "Scout Aleswell Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_06 = GetQuestName(2862) -- "Scout Aleswell Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_07 = GetQuestName(2811) -- "Scout Arrius Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_08 = GetQuestName(2847) -- "Scout Arrius Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_09 = GetQuestName(2829) -- "Scout Arrius Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_10 = GetQuestName(2865) -- "Scout Arrius Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_11 = GetQuestName(2807) -- "Scout Ash Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_12 = GetQuestName(2825) -- "Scout Ash Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_13 = GetQuestName(2861) -- "Scout Ash Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_14 = GetQuestName(2820) -- "Scout Black Boot Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_15 = GetQuestName(2838) -- "Scout Black Boot Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_16 = GetQuestName(2802) -- "Scout Black Boot Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_17 = GetQuestName(2821) -- "Scout Bloodmayne Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_18 = GetQuestName(2839) -- "Scout Bloodmayne Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_19 = GetQuestName(2803) -- "Scout Bloodmayne Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_20 = GetQuestName(2814) -- "Scout Blue Road Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_21 = GetQuestName(2850) -- "Scout Blue Road Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_22 = GetQuestName(2832) -- "Scout Blue Road Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_23 = GetQuestName(2868) -- "Scout Blue Road Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_24 = GetQuestName(2819) -- "Scout Brindle Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_25 = GetQuestName(2837) -- "Scout Brindle Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_26 = GetQuestName(2801) -- "Scout Brindle Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_27 = GetQuestName(2852) -- "Scout Castle Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_28 = GetQuestName(2856) -- "Scout Castle Black Boot"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_29 = GetQuestName(2857) -- "Scout Castle Bloodmayne"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_30 = GetQuestName(2855) -- "Scout Castle Brindle"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_31 = GetQuestName(2853) -- "Scout Castle Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_32 = GetQuestName(2854) -- "Scout Castle Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_33 = GetQuestName(2810) -- "Scout Chalman Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_34 = GetQuestName(2846) -- "Scout Chalman Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_35 = GetQuestName(2828) -- "Scout Chalman Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_36 = GetQuestName(2864) -- "Scout Chalman Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_37 = GetQuestName(2809) -- "Scout Dragonclaw Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_38 = GetQuestName(2827) -- "Scout Dragonclaw Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_39 = GetQuestName(2863) -- "Scout Dragonclaw Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_40 = GetQuestName(2815) -- "Scout Drakelowe Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_41 = GetQuestName(2851) -- "Scout Drakelowe Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_42 = GetQuestName(2833) -- "Scout Drakelowe Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_43 = GetQuestName(2869) -- "Scout Drakelowe Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_44 = GetQuestName(2817) -- "Scout Faregyl Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_45 = GetQuestName(2835) -- "Scout Faregyl Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_46 = GetQuestName(2871) -- "Scout Faregyl Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_47 = GetQuestName(2813) -- "Scout Farragut Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_48 = GetQuestName(2849) -- "Scout Farragut Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_49 = GetQuestName(2831) -- "Scout Farragut Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_50 = GetQuestName(2867) -- "Scout Farragut Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_51 = GetQuestName(2844) -- "Scout Fort Aleswell"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_52 = GetQuestName(2843) -- "Scout Fort Ash"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_53 = GetQuestName(2845) -- "Scout Fort Dragonclaw"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_54 = GetQuestName(2842) -- "Scout Fort Glademist"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_55 = GetQuestName(2841) -- "Scout Fort Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_56 = GetQuestName(2840) -- "Scout Fort Warden"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_57 = GetQuestName(2806) -- "Scout Glademist Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_58 = GetQuestName(2824) -- "Scout Glademist Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_59 = GetQuestName(2860) -- "Scout Glademist Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_60 = GetQuestName(2812) -- "Scout Kingscrest Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_61 = GetQuestName(2848) -- "Scout Kingscrest Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_62 = GetQuestName(2830) -- "Scout Kingscrest Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_63 = GetQuestName(2866) -- "Scout Kingscrest Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_64 = GetQuestName(2805) -- "Scout Rayles Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_65 = GetQuestName(2823) -- "Scout Rayles Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_66 = GetQuestName(2859) -- "Scout Rayles Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_67 = GetQuestName(2818) -- "Scout Roebeck Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_68 = GetQuestName(2836) -- "Scout Roebeck Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_69 = GetQuestName(2800) -- "Scout Roebeck Mine"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_70 = GetQuestName(2804) -- "Scout Warden Farm"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_71 = GetQuestName(2822) -- "Scout Warden Lumbermill"
L.SI_DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_72 = GetQuestName(2858) -- "Scout Warden Mine"

-- Cyrodiil. PvP Quests. Warfront Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_01 = GetQuestName(2927) -- "Capture Castle Alessia"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_02 = GetQuestName(2931) -- "Capture Castle Black Boot"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_03 = GetQuestName(2932) -- "Capture Castle Bloodmayne"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_04 = GetQuestName(2930) -- "Capture Castle Brindle"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_05 = GetQuestName(2928) -- "Capture Castle Faregyl"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_06 = GetQuestName(2929) -- "Capture Castle Roebeck"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_07 = GetQuestName(2919) -- "Capture Fort Aleswell"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_08 = GetQuestName(2918) -- "Capture Fort Ash"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_09 = GetQuestName(2920) -- "Capture Fort Dragonclaw"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_10 = GetQuestName(2917) -- "Capture Fort Glademist"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_11 = GetQuestName(2916) -- "Capture Fort Rayles"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_12 = GetQuestName(2915) -- "Capture Fort Warden"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_13 = GetQuestName(2922) -- "Capture Arrius Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_14 = GetQuestName(2925) -- "Capture Blue Road Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_15 = GetQuestName(2921) -- "Capture Chalman Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_16 = GetQuestName(2926) -- "Capture Drakelowe Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_17 = GetQuestName(2924) -- "Capture Farragut Keep"
L.SI_DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_18 = GetQuestName(2923) -- "Capture Kingscrest Keep"

-- Cyrodiil. PvP Quests. Elder Scrolls Missions
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_01 = GetQuestName(2661) -- "Древний свиток Алма-Румы"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_02 = GetQuestName(2610) -- "Древний свиток Алтадуна"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_03 = GetQuestName(2640) -- "Древний свиток Чима"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_04 = GetQuestName(2658) -- "Древний свиток Гартока"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_05 = GetQuestName(2656) -- "Древний свиток Мнема"
L.SI_DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_06 = GetQuestName(2660) -- "Древний свиток Ни-Мока"

-- Reaper's March. Hadran's Caravan Quests
L.SI_DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_01 = GetQuestName(4668) -- "Гонки ящериц"
L.SI_DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_02 = GetQuestName(4669) -- "Spikeball"
L.SI_DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_03 = GetQuestName(4670) -- "Troll Arena"

-- Event Quests. New Life Festival
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_01 = GetQuestName(5845) -- "Замковое состязание очарования"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_02 = GetQuestName(5855) -- "Пир рыбьего блага"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_03 = GetQuestName(5837) -- "Пляска лавовых ног"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_04 = GetQuestName(5838) -- "Развлечение с комками грязи"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_05 = GetQuestName(5839) -- "Забег сигнальных огней"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_06 = GetQuestName(5811) -- "Ныряние снежного медведя"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_07 = GetQuestName(5856) -- "Удар Каменного зуба"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_08 = GetQuestName(5834) -- "Испытание пятипалого коварства"
L.SI_DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_09 = GetQuestName(5852) -- "Пребывание сирот войны"

-- Event Quests. Jester's Festival
L.SI_DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_01 = GetQuestName(5937) -- "Королевские гулянья"
L.SI_DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_02 = GetQuestName(5931) -- "Благородный гость"
L.SI_DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_03 = GetQuestName(5921) -- "Весенний аромат"

-- Weekly. Trials
L.SI_DQT_WEEKLY_TRIALS_01 = GetQuestName(5087) -- "Assaulting the Citadel"
L.SI_DQT_WEEKLY_TRIALS_02 = GetQuestName(5894) -- "Формирование будущего"
L.SI_DQT_WEEKLY_TRIALS_03 = GetQuestName(5352) -- "Прямо в пасть"
L.SI_DQT_WEEKLY_TRIALS_04 = GetQuestName(5102) -- "Башня мага"
L.SI_DQT_WEEKLY_TRIALS_05 = GetQuestName(5171) -- "The Oldest Ghost"
L.SI_DQT_WEEKLY_TRIALS_06 = GetQuestName(6090) -- "Милосердие святых"
L.SI_DQT_WEEKLY_TRIALS_07 = GetQuestName(6503) -- "The Fight for Kyne's Aegis"
L.SI_DQT_WEEKLY_TRIALS_08 = GetQuestName(6654) -- "Of Stone and Steam"
L.SI_DQT_WEEKLY_TRIALS_09 = GetQuestName(6353) -- "The Return of Alkosh"
L.SI_DQT_WEEKLY_TRIALS_10 = GetQuestName(6192) -- "Woe of the Welkynars"

-- Northern Elsweyr Defense Force
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_01 = GetQuestName(6318) -- "Dark Souls, Mighty Weapons"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_02 = GetQuestName(6346) -- "Dragon Lore: Icehammer's Vault"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_03 = GetQuestName(6347) -- "Dragon Lore: Shroud Hearth"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_04 = GetQuestName(6345) -- "Dragon Lore: Stormcrag Crypt"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_05 = GetQuestName(6342) -- "Goblin Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_06 = GetQuestName(6344) -- "Lamia Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_07 = GetQuestName(6343) -- "Lurcher Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_08 = GetQuestName(6341) -- "Skeleton Demonstration"
L.SI_DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_09 = GetQuestName(6329) -- "Spider Demonstration"

-- Northern Elsweyr Bounty Quests -- Modified by DarkPhalanx
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_01 = GetQuestName(6381) -- "A Dastardly Duo"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_02 = GetQuestName(6377) -- "Sword of the Serpent"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_03 = GetQuestName(6382) -- "The Senche of Decay"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_04 = GetQuestName(6378) -- "The Traders' Terror"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_05 = GetQuestName(6379) -- "A Waking Nightmare"
L.SI_DQT_ELSWEYR_QUESTS_BOUNTY_06 = GetQuestName(6380) -- "Another Day, Another Death"

-- Northern Elsweyr Exploratory Quests -- Modified by DarkPhalanx
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_01 = GetQuestName(6356) -- "Dousing the Daedric Flame"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_02 = GetQuestName(6360) -- "Rifling Through Ruins"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_03 = GetQuestName(6361) -- "The Hungry Cat's Favor"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_04 = GetQuestName(6362) -- "The Serpent's Stampede"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_05 = GetQuestName(6363) -- "Tangled Tea Leaves"
L.SI_DQT_ELSWEYR_QUESTS_EXPLORATORY_06 = GetQuestName(6359) -- "Wisdom in the Winds"

-- Northern Elsweyr Dragon World Events -- Added by DarkPhalanx
L.SI_DQT_ELSWEYR_QUESTS_DRAGONHUNT_01 = GetQuestName(6384) -- "Dragon Hunt"

-- Southern Elsweyr Bounty Quest -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_01 = GetQuestName(6425) -- "Fletching Fetching"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_02 = GetQuestName(6422) -- "A Rogue and His Rice"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_03 = GetQuestName(6423) -- "Dust Smote"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_04 = GetQuestName(6376) -- "Goutfang Pariah"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_05 = GetQuestName(6421) -- "Helping the Healers"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_06 = GetQuestName(6424) -- "Scholarly Observations"

-- Southern Elsweyr Exploratory Quest - Senchal -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_01 = GetQuestName(6419) -- "Tomes of the Tsaesci"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_02 = GetQuestName(6432) -- "Solace By Candlelight"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_03 = GetQuestName(6436) -- "Lilies for Remembrance"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_04 = GetQuestName(6438) -- "An Answer in Blood"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_05 = GetQuestName(6437) -- "Moonlit Mushrooms"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_06 = GetQuestName(6431) -- "Sourcing the Ensorcelled"

-- Southern Elsweyr Dragon Hunts - Dragonguard Sanctum -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DRAGONHUNT_01 = GetQuestName(6444) -- "Dawn of the Dragonguard"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DRAGONHUNT_02 = GetQuestName(6435) -- "The Dragonguard's Quarry"

-- Southern Elsweyr New Moon Quests - Dragonguard Sanctum -- Added by DarkPhalanx
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_07 = GetQuestName(6406) -- "A Lonely Grave"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_08 = GetQuestName(6430) -- "File Under D"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_09 = GetQuestName(6428) -- "Sticks and Bones"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_10 = GetQuestName(6429) -- "Digging Up the Garden"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_11 = GetQuestName(6433) -- "Rude Awakening"
L.SI_DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_12 = GetQuestName(6405) -- "Taking Them to Tusk"

-- Western Skyrim Bounty Quests -- Added by DarkPhalanx
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_01 = GetQuestName(6518) -- "Circle of Cheaters"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_02 = GetQuestName(6526) -- "Feasting in the Dark"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_03 = GetQuestName(6509) -- "Lost Along the Shore"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_04 = GetQuestName(6517) -- "Moonlight Kidnapping"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_05 = GetQuestName(6519) -- "Mother of Shadows"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_06 = GetQuestName(6527) -- "Problem Growth"

-- Western Skyrim Exploratory Quests -- Added by DarkPhalanx
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_01 = GetQuestName(6523) -- "Dwemer Disassembly"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_02 = GetQuestName(6520) -- "Precious Bark"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_03 = GetQuestName(6495) -- "The Preservation of Life"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_04 = GetQuestName(6493) -- "The Strength of Giants"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_05 = GetQuestName(6524) -- "Spiritual Release"
L.SI_DQT_WESTERN_SKYRIM_QUESTS_DELVE_06 = GetQuestName(6494) -- "A Trail Gone Cold"

-- Western Skyrim Harrowstorms -- Added by DarkPhalanx
L.SI_DQT_WESTERN_SKYRIM_QUESTS_HARROWSTORM_01 = GetQuestName(6512) -- "Halt the Harrowstorms"

-- The Reach - Added By DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_01 = GetQuestName(6585) -- "Discarded Treasures"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_02 = GetQuestName(6556) -- "Namira's Perversions"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_03 = GetQuestName(6582) -- "Ruptures in the Reach"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_04 = GetQuestName(6583) -- "The Scholar's Request"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_05 = GetQuestName(6584) -- "Guides to the Deep"
L.SI_DQT_THE_REACH_QUESTS_WORLDBOSS_06 = GetQuestName(6581) -- "Notes of the Void"

-- The Reach Harrowstorms -- Added by DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_HARROWSTORM_01 = GetQuestName(6559) -- "Halt the Harrowstorms"

-- The Reach Exploratory Quests -- Added by DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_DELVE_01 = GetQuestName(6573) -- "Unhatched Menace"
L.SI_DQT_THE_REACH_QUESTS_DELVE_02 = GetQuestName(6557) -- "Wild Talismans"
L.SI_DQT_THE_REACH_QUESTS_DELVE_03 = GetQuestName(6569) -- "What's Hers is Ours"
L.SI_DQT_THE_REACH_QUESTS_DELVE_04 = GetQuestName(6571) -- "Magic Mycology"
L.SI_DQT_THE_REACH_QUESTS_DELVE_05 = GetQuestName(6567) -- "The Tainted Briarheart"
L.SI_DQT_THE_REACH_QUESTS_DELVE_06 = GetQuestName(6572) -- "Strange Contamination"

-- The Reach Ardanir Quests -- Added by DarkPhalanx
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_01 = GetQuestName(6603) -- "Alone in the Dark"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_02 = GetQuestName(6604) -- "Defenders of the Reach"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_03 = GetQuestName(6600) -- "Remnants of the Deep Folk"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_04 = GetQuestName(6605) -- "The Language of the Night"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_05 = GetQuestName(6602) -- "The Light of Arkthzand"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_06 = GetQuestName(6606) -- "The Lost Shrine"
L.SI_DQT_THE_REACH_QUESTS_RESISTANCE_07 = GetQuestName(6601) -- "To Burn Away Evil"

-- Blackwood Delve Quests -- Added by DarkPhalanx
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_01 = GetQuestName(6644) -- "A Proper Blessing"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_02 = GetQuestName(6668) -- "Beauty Amid Danger"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_03 = GetQuestName(6674) -- "Breaking the Chain"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_04 = GetQuestName(6673) -- "Conflict of Interest"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_05 = GetQuestName(6675) -- "Insect Savior"
L.SI_DQT_BLACKWOOD_QUESTS_DELVE_06 = GetQuestName(6665) -- "Shadow Tactics"

-- Blackwood World Boss Quests -- Added by DarkPhalanx
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_01 = GetQuestName(6651) -- "A Reign of Frogs"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_02 = GetQuestName(6653) -- "Call of the Ruinach"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_03 = GetQuestName(6649) -- "Goblin Research"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_04 = GetQuestName(6645) -- "Legend of the Man-Bull"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_05 = GetQuestName(6650) -- "Rites of the Sul-Xan"
L.SI_DQT_BLACKWOOD_QUESTS_WORLDBOSS_06 = GetQuestName(6652) -- "The Trophy-Taker"

-- Deadlands World Boss Quests -- Added by g4m3r7ag
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_01 = GetQuestName(6716) -- "Dangerous Business"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_02 = GetQuestName(6720) -- "Retrieval Gone Awry"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_03 = GetQuestName(6718) -- "Unmaker's Hoard"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_04 = GetQuestName(6719) -- "Careless Contamination"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_05 = GetQuestName(6721) -- "A Paralyzing Lesson"
L.SI_DQT_DEADLANDS_QUESTS_WORLDBOSS_06 = GetQuestName(6717) -- "The Mind's Eye"

-- Deadlands Delve Quests -- Added by g4m3r7ag
L.SI_DQT_DEADLANDS_QUESTS_DELVE_01 = GetQuestName(6714) -- "Clandestine Communications"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_02 = GetQuestName(6715) -- "A Discreet Pickup"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_03 = GetQuestName(6712) -- "Forgotten Grave Goods"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_04 = GetQuestName(6710) -- "Propaganda Suppressed"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_05 = GetQuestName(6713) -- "Flowers in the Folly"
L.SI_DQT_DEADLANDS_QUESTS_DELVE_06 = GetQuestName(6711) -- "Brandfire Reformatory Relics"

-- High Isle World Boss Quests -- Added by g4m3r7ag
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_01 = GetQuestName(6821) -- "Ascendant Shadows"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_02 = GetQuestName(6803) -- "Avarice of the Eldertide"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_03 = GetQuestName(6807) -- "The Sable Knight"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_04 = GetQuestName(6816) -- "The Serpent Caller"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_05 = GetQuestName(6822) -- "A Special Reagent"
L.SI_DQT_HIGH_ISLE_QUESTS_WORLDBOSS_06 = GetQuestName(6808) -- "Wildhorn's Wrath"

-- High Isle Delve Quests -- Added by g4m3r7ag
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_01 = GetQuestName(6809) -- "Arcane Research"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_02 = GetQuestName(6826) -- "Druidic Research"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_03 = GetQuestName(6805) -- "A Final Peace"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_04 = GetQuestName(6825) -- "Pirate Problems"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_05 = GetQuestName(6818) -- "Prison Problems"
L.SI_DQT_HIGH_ISLE_QUESTS_DELVE_06 = GetQuestName(6815) -- "Seek and Destroy"

-- High Isle Volcanic Vents Quests -- Added by g4m3r7ag
L.SI_DQT_HIGH_ISLE_QUESTS_VOLCANIC_VENTS_01 = GetQuestName(6812) -- "Venting the Threat"

-- High Isle Tales of Tribute Quests -- Added by g4m3r7ag
L.SI_DQT_TALES_OF_TRIBUTE_QUESTS_01 = GetQuestName(6831) -- "Cards Across the Continent"
L.SI_DQT_TALES_OF_TRIBUTE_QUESTS_02 = GetQuestName(6832) -- "Dueling Tributes"

-- Galen World Boss Quests -- Added by g4m3r7ag
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_01 = GetQuestName(6886) -- "Flower Fancier"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_02 = GetQuestName(6887) -- "Helpful Handbills"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_03 = GetQuestName(6884) -- "Volcanic Virtuoso"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_04 = GetQuestName(6883) -- "Radiant Souvenirs"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_05 = GetQuestName(6888) -- "Marking the Path"
L.SI_DQT_GALEN_QUESTS_WORLDBOSS_06 = GetQuestName(6885) -- "Critter Capture"

-- Galen Delve Quests -- Added by g4m3r7ag
L.SI_DQT_GALEN_QUESTS_DELVE_01 = GetQuestName(6878) -- "Sunflower Stamina"
L.SI_DQT_GALEN_QUESTS_DELVE_02 = GetQuestName(6891) -- "Three-Pronged Approach"
L.SI_DQT_GALEN_QUESTS_DELVE_03 = GetQuestName(6881) -- "A Wailing Wood"
L.SI_DQT_GALEN_QUESTS_DELVE_04 = GetQuestName(6890) -- "Recovered Relics"
L.SI_DQT_GALEN_QUESTS_DELVE_05 = GetQuestName(6889) -- "The Moth Study"
L.SI_DQT_GALEN_QUESTS_DELVE_06 = GetQuestName(6892) -- "Shrines on Shaky Ground"

-- Galen Volcanic Vents Quests -- Added by g4m3r7ag
L.SI_DQT_GALEN_QUESTS_VOLCANIC_VENTS_01 = GetQuestName(6901) -- "Imminent Hazard"

for stringId, translation in pairs(L) do
    SafeAddString(_G[stringId], translation, 0)
end
